"""
Hardware keep-out penalty (``CurveHardwareKeepout``).

Motivation
----------
The HBT clearance viewer's swept-solid contact check showed that the M7
champion's coils intersect in-vessel hardware no existing objective knows
about: 4/10 coils clip the Mirnov sensor arrays and one clips a solenoid
mount (vessel/shell are already covered by ``CurveSurfaceDistance``; the
legacy banana frame channel is moot). A 360-degree rigid toroidal phase
scan proved no rotation clears the hardware — the 5/10-contact minima
repeat at the machine's 36-degree period with the current registration
already optimal — so the coil shapes must be steered away during
optimisation.

This module is that steering term: the mathematical structure of
:class:`simsopt.geo.curveobjectives.CurveSurfaceDistance` (quadratic
hinge on pairwise distance, integrated along each curve and over the
obstacle surface), with the surface quadrature replaced by a fixed point
cloud sampled over the hardware surfaces
(``CAD/banana_coils/hbt_clearance_viewer/tools/hardware_keepout.json``,
generated by ``export_hardware_keepout.py`` with sha-bound provenance and
cross-validated against the viewer's parry-verified contact verdict).

Mathematical form
-----------------
For curves :math:`\\gamma^{(c)}` on ``N`` quadpoints and hardware points
:math:`p_k`, each representing a surface patch of area :math:`w` (the
sampling ``spacing_m`` squared),

.. math::
    J = \\sum_{c} \\frac{1}{N} \\sum_{i=1}^{N}
        \\lVert \\gamma'^{(c)}_i \\rVert \\sum_{k}
        \\frac{w}{d_{\\min}^{2}}
        \\left(\\frac{\\max(0,\\; d_{\\min} -
        \\lVert \\gamma^{(c)}_i - p_k \\rVert)}{d_{\\min}}\\right)^{2},

the ``CurveSurfaceDistance`` hinge-squared integral
:math:`\\sum_c \\int\\!\\!\\int \\max(0, d_{\\min} - d)^2 \\, dl \\, ds`
**nondimensionalised by** :math:`d_{\\min}^4`: violation depth is measured
in units of the threshold and patch area in units of the threshold
squared, so ``J`` reads as coil-metres in violation weighted by relative
depth squared. The raw m^5 integral is numerically minuscule for real
violations (a 21 mm-deep sensor-array intrusion of the M17b run measured
``5.1e-08``), which let a weight of ``2.4e5`` contribute only ``0.012``
to the objective — the optimizer ignored the hardware entirely and ALM
feasibility tolerances would equally have swallowed it. In these
normalised units the same intrusion measures ``~0.2``, so penalty
weights of order ``1e1–1e3`` and the schema's ``alm_scale = 1`` exert
real pressure. Clear of the cloud is exactly ``J = 0`` in either
convention.

:math:`d_{\\min}` is measured from the coil *centerline*: the optimiser
sees centerlines but the swept U-channel is what collides, so the
threshold is the bracket half-diagonal (29x20 mm -> 17.6 mm) plus a
safety margin (``HARDWARE_KEEPOUT_MIN_DISTANCE_M`` in
``hardware_contracts.py``; same value recorded in the cloud JSON as
``recommended_min_distance_m``).

Design notes
------------
* The penalty must see the **full symmetry-expanded banana coil set**:
  each copy meets different hardware (the M7 verdict touches coils
  2/3/6/9, not the base curve alone). Gradients flow to the shared dofs
  through each copy's ``dgamma_by_dcoeff_vjp``, exactly as in
  ``CurveCurveDistance``. TF curves are deliberately excluded — they are
  fixed machine coils whose permanent proximity would add un-optimisable
  constant violation.
* The cloud is static: it is sorted by toroidal angle and split into
  equal-size chunks (the last padded with far-away sentinel points whose
  hinge — and therefore gradient — is identically zero). Equal shapes
  mean a single JIT specialisation; toroidal sorting keeps chunks
  spatially coherent so pruning discards distant ones.
* Candidate (curve, chunk) pairs are pruned with a self-contained
  axis-aligned bounding-box test inflated by :math:`d_{\\min}` — a
  conservative superset of the active pairs, so pruning is exact for the
  hinge (pairs farther than :math:`d_{\\min}` contribute exactly zero).
* The ``max(., 0)^2`` hinge is :math:`C^1` at the threshold; the
  double-where guard protects the backward pass if a quadpoint ever
  coincides with a cloud point (sqrt(0) subgradient), the same pattern
  as ``self_intersect.py``.
"""

from __future__ import annotations

import json

import numpy as np
from jax import grad
import jax.numpy as jnp

from simsopt._core import Optimizable
from simsopt._core.derivative import derivative_dec
from simsopt.geo.jit import jit

#: Sentinel coordinate for chunk padding — far from any machine geometry
#: (HBT-EP fits in ~1.3 m), so padded points never activate the hinge.
_PAD_COORDINATE = 1.0e3


def hardware_keepout_pure(gammac, lc, points, point_weight, minimum_distance):
    """Curve-vs-hardware-cloud hinge penalty, JAX-pure.

    Parameters
    ----------
    gammac : (N, 3) array
        Curve quadpoints.
    lc : (N, 3) array
        Curve tangents d(gamma)/ds.
    points : (P, 3) array
        Hardware surface sample points (one chunk).
    point_weight : float
        Surface patch area each point represents (sampling spacing^2), m^2.
    minimum_distance : float
        Centerline keep-out threshold, m.
    """
    dist_sq = jnp.sum((gammac[:, None, :] - points[None, :, :]) ** 2, axis=2)
    safe = jnp.where(dist_sq > 0.0, dist_sq, 1.0)
    dists = jnp.where(dist_sq > 0.0, jnp.sqrt(safe), 0.0)
    alen = jnp.linalg.norm(lc, axis=1)[:, None]
    # Depth in units of d_min, patch area in units of d_min^2 (see module
    # docstring): keeps real violations O(0.1-1) instead of O(1e-8) m^5.
    viol_rel = jnp.maximum(minimum_distance - dists, 0.0) / minimum_distance
    return jnp.sum(
        alen * (point_weight / minimum_distance**2) * viol_rel**2
    ) / gammac.shape[0]


class CurveHardwareKeepout(Optimizable):
    r"""
    Penalty steering the banana coils away from fixed in-vessel hardware
    (sensor arrays, solenoid mounts, REMC mounts) — the keep-out analogue
    of :class:`simsopt.geo.curveobjectives.CurveSurfaceDistance` with the
    surface quadrature replaced by a static sampled point cloud.

    Parameters
    ----------
    curves : list of simsopt.geo.curve.Curve
        Full symmetry-expanded banana coil set (each copy meets different
        hardware). Each must expose ``gamma()``, ``gammadash()``,
        ``dgamma_by_dcoeff_vjp`` and ``dgammadash_by_dcoeff_vjp``.
    points : (P, 3) array
        Hardware surface sample points in the machine metre frame
        (see :func:`load_hardware_keepout`).
    minimum_distance : float
        Centerline keep-out threshold, m
        (``HARDWARE_KEEPOUT_MIN_DISTANCE_M``).
    point_weight : float
        Surface patch area per point (sampling spacing^2), m^2.
    chunk_size : int, optional
        Cloud chunk size for candidate pruning / single-shape JIT.
    """

    def __init__(self, curves, points, minimum_distance, point_weight,
                 chunk_size=8192):
        self.curves = curves
        self.minimum_distance = float(minimum_distance)
        self.point_weight = float(point_weight)

        pts = np.ascontiguousarray(np.asarray(points, dtype=np.float64))
        if pts.ndim != 2 or pts.shape[1] != 3 or pts.shape[0] == 0:
            raise ValueError(
                f"points must be a non-empty (P, 3) array, got {pts.shape}")
        # Toroidal sort -> spatially coherent chunks -> effective pruning.
        order = np.argsort(np.arctan2(pts[:, 1], pts[:, 0]))
        pts = pts[order]
        pad = (-len(pts)) % chunk_size
        if pad:
            pts = np.vstack([pts, np.full((pad, 3), _PAD_COORDINATE)])
        self._chunks_np = [
            pts[i:i + chunk_size] for i in range(0, len(pts), chunk_size)
        ]
        self._chunks = [jnp.asarray(c) for c in self._chunks_np]
        # Static per-chunk AABBs over the REAL points only (pads excluded so
        # they never widen a chunk's box).
        self._chunk_bounds = []
        for chunk in self._chunks_np:
            real = chunk[np.any(chunk != _PAD_COORDINATE, axis=1)]
            self._chunk_bounds.append((real.min(axis=0), real.max(axis=0)))

        self.J_jax = jit(lambda gammac, lc, pts_: hardware_keepout_pure(
            gammac, lc, pts_, self.point_weight, self.minimum_distance))
        self.dJ_dgamma = jit(
            lambda gammac, lc, pts_: grad(self.J_jax, argnums=0)(gammac, lc, pts_))
        self.dJ_dlc = jit(
            lambda gammac, lc, pts_: grad(self.J_jax, argnums=1)(gammac, lc, pts_))
        self.candidates = None
        super().__init__(depends_on=curves)

    def recompute_bell(self, parent=None):
        self.candidates = None

    def compute_candidates(self):
        """(curve, chunk) pairs whose inflated AABBs overlap — a conservative
        superset of pairs with any quadpoint within ``minimum_distance`` of a
        cloud point, so the pruning is exact for the hinge."""
        if self.candidates is None:
            d = self.minimum_distance
            candidates = []
            for i, curve in enumerate(self.curves):
                g = curve.gamma()
                glo, ghi = g.min(axis=0) - d, g.max(axis=0) + d
                for j, (clo, chi) in enumerate(self._chunk_bounds):
                    if np.all(glo <= chi) and np.all(clo <= ghi):
                        candidates.append((i, j))
            self.candidates = candidates

    def shortest_distance(self):
        """Minimum quadpoint-to-cloud distance over all curves, m. Diagnostic
        only (NumPy); pads sit ~1 km away and cannot win the minimum."""
        from scipy.spatial.distance import cdist
        return min(
            float(np.min(cdist(c.gamma(), chunk)))
            for c in self.curves
            for chunk in self._chunks_np
        )

    # ── Optimizable API ────────────────────────────────────────────────
    def J(self):
        self.compute_candidates()
        res = 0.0
        for i, j in self.candidates:
            gammac = self.curves[i].gamma()
            lc = self.curves[i].gammadash()
            res += float(self.J_jax(gammac, lc, self._chunks[j]))
        return res

    @derivative_dec
    def dJ(self):
        self.compute_candidates()
        dgamma_vecs = [np.zeros_like(c.gamma()) for c in self.curves]
        dlc_vecs = [np.zeros_like(c.gammadash()) for c in self.curves]
        for i, j in self.candidates:
            gammac = self.curves[i].gamma()
            lc = self.curves[i].gammadash()
            dgamma_vecs[i] += np.asarray(self.dJ_dgamma(gammac, lc, self._chunks[j]))
            dlc_vecs[i] += np.asarray(self.dJ_dlc(gammac, lc, self._chunks[j]))
        res = [
            self.curves[i].dgamma_by_dcoeff_vjp(dgamma_vecs[i])
            + self.curves[i].dgammadash_by_dcoeff_vjp(dlc_vecs[i])
            for i in range(len(self.curves))
        ]
        return sum(res)

    return_fn_map = {'J': J, 'dJ': dJ}


def load_hardware_keepout(path):
    """Load a ``hardware_keepout.json`` produced by
    ``hbt_clearance_viewer/tools/export_hardware_keepout.py``.

    Returns ``(points, point_weight, recommended_min_distance, provenance)``
    where ``points`` is the concatenated (P, 3) float64 cloud over all
    groups, ``point_weight`` the per-point surface patch area (spacing^2,
    m^2), ``recommended_min_distance`` the centerline threshold recorded by
    the exporter, and ``provenance`` the raw provenance block.
    """
    with open(path) as f:
        data = json.load(f)
    if data.get("schema_version") != 1:
        raise ValueError(
            f"unsupported keepout schema_version {data.get('schema_version')!r}")
    if data.get("frame") != "machine_metres_zup" or data.get("units") != "m":
        raise ValueError(
            f"keepout frame/units mismatch: {data.get('frame')!r}/"
            f"{data.get('units')!r}; expected machine_metres_zup metres "
            f"(the coils' frame)")
    points = np.concatenate(
        [np.asarray(group["points"], dtype=np.float64) for group in data["groups"]],
        axis=0,
    )
    spacing = float(data["spacing_m"])
    return (
        points,
        spacing * spacing,
        float(data["recommended_min_distance_m"]),
        data["provenance"],
    )
