"""
Hardware keep-out penalty (``CurveHardwareKeepout``).

Motivation
----------
The HBT clearance viewer's swept-solid contact check showed that the M7
champion's coils intersect in-vessel hardware no existing objective knows
about: 4/10 coils clip the Mirnov sensor arrays and one clips a solenoid
mount. The point-cloud objective below covers the sampled shells, sensors,
solenoid, REMC, limiter, and quartz-spool hardware. Vessel contact is steered
by the analytic vessel-envelope term; frame/sample remain documented gate-only
classes checked by the direct promotion oracle. A 360-degree rigid toroidal
phase scan proved no rotation clears the hardware — the 5/10-contact minima
repeat at the machine's 36-degree period with the current registration
already optimal — so the coil shapes must be steered away during
optimisation.

This module is that steering term: the mathematical structure of
:class:`simsopt.geo.curveobjectives.CurveSurfaceDistance` (quadratic
hinge on pairwise distance, integrated along each curve and over the
obstacle surface), with the surface quadrature replaced by a fixed point
cloud sampled over the hardware surfaces
(``CAD/banana_coils/hbt_clearance_viewer/tools/hardware_keepout.json``,
generated by ``export_hardware_keepout.py`` with sha-bound provenance and
cross-validated against the viewer's parry-verified contact verdict).

Mathematical form
-----------------
For curves :math:`\\gamma^{(c)}` on ``N`` quadpoints and hardware points
:math:`p_k`, each representing a surface patch of area :math:`w` (the
sampling ``spacing_m`` squared),

.. math::
    J = \\sum_{c} \\frac{1}{N} \\sum_{i=1}^{N}
        \\lVert \\gamma'^{(c)}_i \\rVert \\sum_{k}
        \\frac{w}{d_{\\min}^{2}}
        \\left(\\frac{\\max(0,\\; d_{\\min} -
        \\lVert \\gamma^{(c)}_i - p_k \\rVert)}{d_{\\min}}\\right)^{2},

the ``CurveSurfaceDistance`` hinge-squared integral
:math:`\\sum_c \\int\\!\\!\\int \\max(0, d_{\\min} - d)^2 \\, dl \\, ds`
**nondimensionalised by** :math:`d_{\\min}^4`: violation depth is measured
in units of the threshold and patch area in units of the threshold
squared, so ``J`` reads as coil-metres in violation weighted by relative
depth squared. The raw m^5 integral is numerically minuscule for real
violations (a 21 mm-deep sensor-array intrusion of the M17b run measured
``5.1e-08``), which let a weight of ``2.4e5`` contribute only ``0.012``
to the objective — the optimizer ignored the hardware entirely and ALM
feasibility tolerances would equally have swallowed it. In these
normalised units the same intrusion measures ``~0.2``, so penalty
weights of order ``1e1–1e3`` and the schema's ``alm_scale = 1`` exert
real pressure. Clear of the cloud is exactly ``J = 0`` in either
convention.

:math:`d_{\\min}` is measured from the coil *centerline*: the optimiser
sees centerlines but the swept Type KK outer channel is what collides, so
the threshold is the outer-channel half-diagonal (46.1772x16.256 mm ->
24.48 mm) plus a safety margin (``HARDWARE_KEEPOUT_MIN_DISTANCE_M`` in
``hardware_contracts.py``; same value recorded in the cloud JSON as
``recommended_min_distance_m``).

Design notes
------------
* The penalty must see the **full symmetry-expanded banana coil set**:
  each copy meets different hardware (the M7 verdict touches coils
  2/3/6/9, not the base curve alone). Gradients flow to the shared dofs
  through each copy's ``dgamma_by_dcoeff_vjp``, exactly as in
  ``CurveCurveDistance``. TF curves are deliberately excluded — they are
  fixed machine coils whose permanent proximity would add un-optimisable
  constant violation.
* The cloud is static: it is sorted by toroidal angle and split into
  equal-size chunks (the last padded with far-away sentinel points whose
  hinge — and therefore gradient — is identically zero). Equal shapes
  mean a single JIT specialisation; toroidal sorting keeps chunks
  spatially coherent so pruning discards distant ones.
* Candidate (curve, chunk) pairs are pruned with a self-contained
  axis-aligned bounding-box test inflated by :math:`d_{\\min}` — a
  conservative superset of the active pairs, so pruning is exact for the
  hinge (pairs farther than :math:`d_{\\min}` contribute exactly zero).
* The ``max(., 0)^2`` hinge is :math:`C^1` at the threshold; the
  double-where guard protects the backward pass if a quadpoint ever
  coincides with a cloud point (sqrt(0) subgradient), the same pattern
  as ``self_intersect.py``.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from jax import grad
import jax.numpy as jnp

from banana_opt.hardware_contracts import (
    BANANA_WINDING_SURFACE_MAJOR_RADIUS_M,
    HARDWARE_KEEPOUT_SAFETY_MARGIN_M,
    TYPE_KK_OUTER_CHANNEL_HALF_DEPTH_NORMAL_M,
    TYPE_KK_OUTER_CHANNEL_HALF_WIDTH_BINORMAL_M,
    VACUUM_VESSEL_MAJOR_RADIUS_M,
    VACUUM_VESSEL_MINOR_RADIUS_M,
)
from banana_opt.coil_order_upgrade import realized_cws_winding_radii
from simsopt._core import Optimizable
from simsopt._core.derivative import derivative_dec
from simsopt.geo.jit import jit

#: Sentinel coordinate for chunk padding — far from any machine geometry
#: (HBT-EP fits in ~1.3 m), so padded points never activate the hinge.
_PAD_COORDINATE = 1.0e3


def resolve_keepout_winding_r0(banana_coils):
    """Return the realized CWS winding major radius, or the spec default.

    Hardware and vessel keepout use this radius to orient their Type-KK
    U-channel frames; warm CWS resumes must use the torus embedded in the seed.
    """
    realized_winding_radii = realized_cws_winding_radii(banana_coils)
    if realized_winding_radii is None:
        return BANANA_WINDING_SURFACE_MAJOR_RADIUS_M
    return realized_winding_radii[0]


def live_winding_r0(curves, fallback):
    """LIVE winding major radius of the curves' embedded CWS torus, or ``fallback``.

    The keepout and buildability steering terms hold *curves* (a symmetry-
    expanded family or a single master), unlike :func:`resolve_keepout_winding_r0`
    /:func:`realized_cws_winding_radii`, which read a *coil* list. For a CWS
    lineage the winding major radius is ``surf.get_rc(0, 0)`` of the master curve
    sharing the family's winding surface; with ``--winding-surface-free-r0`` that
    DOF moves during optimisation, so reading it on every evaluation keeps the
    U-channel frame measured about the TRUE moving torus instead of a value
    frozen at objective construction (B1.3 value-live). The first curve exposing
    a ``surf`` with ``get_rc`` is the master (``RotatedCurve`` copies wrap it and
    expose neither); non-CWS lineages (e.g. ``CurveXYZFourier``) have no such
    surface, so ``fallback`` -- the constructor's frozen ``winding_r0`` -- is
    returned unchanged.
    """
    for curve in curves:
        surf = getattr(curve, "surf", None)
        if surf is not None and hasattr(surf, "get_rc"):
            return float(surf.get_rc(0, 0))
    return fallback


# Surface quadrature over the swept rectangular Type KK U-channel sample box.
# The triplets are coefficients of (half segment, half width, half depth):
# 8 corners, 6 face centers, and 12 edge midpoints.  These points are a
# deterministic low-order surface proxy for the exact swept solid; the parry3d
# audit remains the final oracle.
_SWEPT_SURFACE_QUADRATURE = np.array(
    [
        *(
            (sweep, width, depth)
            for sweep in (-1.0, 1.0)
            for width in (-1.0, 1.0)
            for depth in (-1.0, 1.0)
        ),
        (-1.0, 0.0, 0.0),
        (1.0, 0.0, 0.0),
        (0.0, -1.0, 0.0),
        (0.0, 1.0, 0.0),
        (0.0, 0.0, -1.0),
        (0.0, 0.0, 1.0),
        *(
            (sweep, width, 0.0)
            for sweep in (-1.0, 1.0)
            for width in (-1.0, 1.0)
        ),
        *(
            (sweep, 0.0, depth)
            for sweep in (-1.0, 1.0)
            for depth in (-1.0, 1.0)
        ),
        *(
            (0.0, width, depth)
            for width in (-1.0, 1.0)
            for depth in (-1.0, 1.0)
        ),
    ],
    dtype=np.float64,
)


@dataclass(frozen=True)
class HardwareSdfGroup:
    """One CAD-derived distance grid in the machine metre frame."""

    label: str
    grid: np.ndarray
    origin_m: np.ndarray
    spacing_m: float
    narrow_band_m: float
    effective_margin_m: float
    sign_method: str


@dataclass(frozen=True)
class HardwareSdfData:
    """Manifest-bound hardware SDF payload consumed by CurveHardwareSdfKeepout."""

    manifest_path: str
    data_path: str
    manifest_sha256: str
    data_sha256: str
    groups: tuple[HardwareSdfGroup, ...]
    safety_margin_m: float
    error_budget_m: dict[str, float]
    documented_gate_only: dict[str, object]
    covered_by_other_in_loop: dict[str, object]
    provenance: dict[str, object]

    @property
    def group_labels(self) -> tuple[str, ...]:
        return tuple(group.label for group in self.groups)

    @property
    def sign_methods(self) -> dict[str, str]:
        return {group.label: group.sign_method for group in self.groups}

    @property
    def effective_margin_m(self) -> float:
        return max(group.effective_margin_m for group in self.groups)


def _normalize(v):
    """Row-wise unit vectors with an eps guard (rows are never truly zero for a
    real coil: tangent and radial directions are well defined everywhere)."""
    return v / jnp.linalg.norm(v, axis=-1, keepdims=True).clip(1e-30)


def _bracket_frame(gammac, winding_r0):
    """Per-quadpoint as-built U-channel frame, an exact differentiable port of
    the viewer's ``geom::frames`` (the swept-solid the oracle measures).

    Returns ``(tangent, tangential, radial, half_seg)`` with row i giving the
    bracket basis at quadpoint i: ``tangential`` is the cross-section width
    direction (pack binormal), ``radial`` the depth direction (toward/from the
    winding major axis at ``winding_r0``), ``tangent`` the sweep direction, and
    ``half_seg`` half the local along-sweep span (so adjacent boxes tile).
    """
    nxt = jnp.roll(gammac, -1, axis=0)
    prv = jnp.roll(gammac, 1, axis=0)
    tangent = _normalize(nxt - prv)
    phi = jnp.arctan2(gammac[:, 1], gammac[:, 0])
    axis = jnp.stack(
        [winding_r0 * jnp.cos(phi), winding_r0 * jnp.sin(phi),
         jnp.zeros_like(phi)],
        axis=1,
    )
    radial0 = _normalize(gammac - axis)
    tangential = _normalize(jnp.cross(tangent, radial0))
    radial = _normalize(jnp.cross(tangential, tangent))
    half_seg = 0.25 * jnp.linalg.norm(nxt - prv, axis=1)
    return tangent, tangential, radial, half_seg


def _bracket_corners(gammac, half_w, half_d, winding_r0):
    """Eight Type KK envelope corners per quadpoint in the viewer frame."""
    tangent, tangential, radial, half_seg = _bracket_frame(gammac, winding_r0)
    corners = []
    for sweep_sign in (-1.0, 1.0):
        for width_sign in (-1.0, 1.0):
            for depth_sign in (-1.0, 1.0):
                corners.append(
                    gammac
                    + sweep_sign * half_seg[:, None] * tangent
                    + width_sign * half_w * tangential
                    + depth_sign * half_d * radial
                )
    return jnp.concatenate(corners, axis=0)


def swept_channel_surface_points(gammac, half_w, half_d, winding_r0):
    """Sample the swept Type KK U-channel surface in the viewer-matched frame.

    Returns ``N * 26`` points: corners, face centers, and edge midpoints for the
    local swept box at each curve station.  The exact CAD/parry swept-solid
    checker remains the oracle; this deterministic sample set is the optimizer
    proxy used by the SDF backend.
    """
    tangent, tangential, radial, half_seg = _bracket_frame(gammac, winding_r0)
    coeffs = jnp.asarray(_SWEPT_SURFACE_QUADRATURE)
    sweep = coeffs[:, 0]
    width = coeffs[:, 1]
    depth = coeffs[:, 2]
    samples = (
        gammac[:, None, :]
        + sweep[None, :, None] * half_seg[:, None, None] * tangent[:, None, :]
        + width[None, :, None] * half_w * tangential[:, None, :]
        + depth[None, :, None] * half_d * radial[:, None, :]
    )
    return samples.reshape((-1, 3))


def vessel_envelope_clearance_pure(gammac, half_w, half_d, winding_r0,
                                   vessel_r0, vessel_minor_radius):
    """Signed clearance from the Type KK swept envelope to the vessel torus.

    Positive means all sampled envelope corners are inside the vessel tube;
    negative means at least one corner pokes outside the vessel wall.
    """
    corners = _bracket_corners(gammac, half_w, half_d, winding_r0)
    major_radius = jnp.sqrt(corners[:, 0] ** 2 + corners[:, 1] ** 2)
    tube_radius = jnp.sqrt(
        (major_radius - vessel_r0) ** 2 + corners[:, 2] ** 2
    )
    return jnp.min(vessel_minor_radius - tube_radius)


def vessel_envelope_keepout_pure(gammac, half_w, half_d, minimum_clearance,
                                 winding_r0, vessel_r0, vessel_minor_radius):
    """Margin-normalized vessel-wall penalty for the Type KK swept envelope."""
    corners = _bracket_corners(gammac, half_w, half_d, winding_r0)
    major_radius = jnp.sqrt(corners[:, 0] ** 2 + corners[:, 1] ** 2)
    tube_radius = jnp.sqrt(
        (major_radius - vessel_r0) ** 2 + corners[:, 2] ** 2
    )
    clearance = vessel_minor_radius - tube_radius
    scale = jnp.maximum(minimum_clearance, 1.0e-6)
    violation = jnp.maximum(minimum_clearance - clearance, 0.0) / scale
    return jnp.mean(violation ** 2)


def vessel_available_envelope_reward_pure(gammac, half_w, half_d,
                                          minimum_clearance, winding_r0,
                                          vessel_r0, vessel_minor_radius):
    """Bounded reward for using positive-clearance vessel envelope volume."""
    corners = _bracket_corners(gammac, half_w, half_d, winding_r0)
    major_radius = jnp.sqrt(corners[:, 0] ** 2 + corners[:, 1] ** 2)
    tube_radius = jnp.sqrt(
        (major_radius - vessel_r0) ** 2 + corners[:, 2] ** 2
    )
    usable_radius = jnp.maximum(vessel_minor_radius - minimum_clearance, 1.0e-6)
    safe_tube_radius = jnp.clip(tube_radius, 0.0, usable_radius)
    fill_fraction = safe_tube_radius / usable_radius
    return -jnp.mean(fill_fraction ** 2)


def hardware_keepout_pure(gammac, points, point_weight, half_w, half_d,
                          margin, winding_r0):
    r"""Curve-vs-hardware hinge penalty on the **as-built U-channel envelope**.

    Unlike a centerline-distance penalty padded by a single isotropic number,
    this measures the distance from each hardware point to the swept rectangular
    bracket (``±half_w`` along the pack binormal, ``±half_d`` along the pack
    normal, swept along the tangent), oriented exactly as the viewer's
    swept-solid oracle. The hinge then activates within ``margin`` of that real
    metal surface. Optimising it therefore moves the *actual* contacting edge,
    not a proxy point the bracket may not even reach.

    Parameters
    ----------
    gammac : (N, 3) array
        Curve quadpoints (the frame is derived from these, so the gradient
        flows entirely through ``gamma``; no separate tangent input).
    points : (P, 3) array
        Hardware surface sample points (one chunk).
    point_weight : float
        Surface patch area each point represents (sampling spacing^2), m^2.
    half_w, half_d : float
        Bracket cross-section half-extents (binormal width / normal depth), m.
    margin : float
        Safety clearance required *beyond* the metal envelope, m.
    winding_r0 : float
        Winding major radius defining the radial frame direction (must match
        the artifact ``winding_surface.r0_m`` the oracle uses).
    """
    tangent, tangential, radial, half_seg = _bracket_frame(gammac, winding_r0)
    d = points[None, :, :] - gammac[:, None, :]              # (N, P, 3)
    a = jnp.abs(jnp.sum(d * tangent[:, None, :], axis=2))    # along sweep
    b = jnp.abs(jnp.sum(d * tangential[:, None, :], axis=2))  # along width
    c = jnp.abs(jnp.sum(d * radial[:, None, :], axis=2))     # along depth
    da = jnp.maximum(a - half_seg[:, None], 0.0)
    db = jnp.maximum(b - half_w, 0.0)
    dc = jnp.maximum(c - half_d, 0.0)
    box_sq = da ** 2 + db ** 2 + dc ** 2                     # (N, P) to box i
    # Distance from each hardware point to the swept solid = nearest box.
    solid_sq = jnp.min(box_sq, axis=0)                      # (P,)
    safe = jnp.where(solid_sq > 0.0, solid_sq, 1.0)
    solid = jnp.where(solid_sq > 0.0, jnp.sqrt(safe), 0.0)
    viol_rel = jnp.maximum(margin - solid, 0.0) / margin
    return jnp.sum(point_weight * viol_rel ** 2) / margin ** 2


def _sdf_trilinear(grid, origin_m, spacing_m, points, outside_value):
    """Trilinear interpolation for a single regular SDF grid.

    Points outside the grid are assigned ``outside_value``.  The caller chooses
    that value from the manifest contract; narrow-band hardware grids require
    the band to cover the effective keepout margin, so outside-grid points are
    safely beyond the active collision shell.
    """
    grid_shape = jnp.asarray(grid.shape)
    local = (points - origin_m) / spacing_m
    lower_f = jnp.floor(local)
    lower = lower_f.astype(jnp.int32)
    valid = jnp.all((local >= 0.0) & (local <= (grid_shape - 1)), axis=1)
    lower = jnp.clip(lower, 0, grid_shape - 2)
    frac = jnp.clip(local - lower_f, 0.0, 1.0)

    i0, j0, k0 = lower[:, 0], lower[:, 1], lower[:, 2]
    i1, j1, k1 = i0 + 1, j0 + 1, k0 + 1
    tx, ty, tz = frac[:, 0], frac[:, 1], frac[:, 2]

    c000 = grid[i0, j0, k0]
    c100 = grid[i1, j0, k0]
    c010 = grid[i0, j1, k0]
    c110 = grid[i1, j1, k0]
    c001 = grid[i0, j0, k1]
    c101 = grid[i1, j0, k1]
    c011 = grid[i0, j1, k1]
    c111 = grid[i1, j1, k1]

    c00 = c000 * (1.0 - tx) + c100 * tx
    c10 = c010 * (1.0 - tx) + c110 * tx
    c01 = c001 * (1.0 - tx) + c101 * tx
    c11 = c011 * (1.0 - tx) + c111 * tx
    c0 = c00 * (1.0 - ty) + c10 * ty
    c1 = c01 * (1.0 - ty) + c11 * ty
    value = c0 * (1.0 - tz) + c1 * tz
    return jnp.where(valid, value, outside_value)


def hardware_sdf_keepout_pure(gammac, grid, origin_m, spacing_m,
                              effective_margin_m, half_w, half_d,
                              winding_r0):
    """SDF-backed keepout on sampled swept Type KK surface points."""
    surface_points = swept_channel_surface_points(
        gammac, half_w, half_d, winding_r0
    )
    scale = jnp.maximum(effective_margin_m, 1.0e-6)
    phi = _sdf_trilinear(
        grid,
        origin_m,
        spacing_m,
        surface_points,
        outside_value=effective_margin_m,
    )
    violation = jnp.maximum(effective_margin_m - phi, 0.0) / scale
    return jnp.mean(violation ** 2)


def hardware_sdf_free_space_reward_pure(gammac, grid, origin_m, spacing_m,
                                        effective_margin_m, half_w, half_d,
                                        winding_r0):
    """Bounded reward for sampled swept Type KK surface clearance in CAD SDF."""
    surface_points = swept_channel_surface_points(
        gammac, half_w, half_d, winding_r0
    )
    scale = jnp.maximum(effective_margin_m, 1.0e-6)
    phi = _sdf_trilinear(
        grid,
        origin_m,
        spacing_m,
        surface_points,
        outside_value=effective_margin_m,
    )
    clearance_fraction = jnp.clip(phi, 0.0, effective_margin_m) / scale
    return -jnp.mean(clearance_fraction ** 2)


class CurveHardwareKeepout(Optimizable):
    r"""
    Penalty steering the banana coils away from fixed in-vessel hardware
    sampled in ``hardware_keepout.json`` (shells, sensors, solenoid, REMC,
    limiter, and quartz-spool rings) — the keep-out analogue of
    :class:`simsopt.geo.curveobjectives.CurveSurfaceDistance` with the surface
    quadrature replaced by a static sampled point cloud.

    Parameters
    ----------
    curves : list of simsopt.geo.curve.Curve
        Full symmetry-expanded banana coil set (each copy meets different
        hardware). Each must expose ``gamma()``, ``gammadash()``,
        ``dgamma_by_dcoeff_vjp`` and ``dgammadash_by_dcoeff_vjp``.
    points : (P, 3) array
        Hardware surface sample points in the machine metre frame
        (see :func:`load_hardware_keepout`).
    minimum_distance : float
        Centerline keep-out threshold, m
        (``HARDWARE_KEEPOUT_MIN_DISTANCE_M``).
    point_weight : float
        Surface patch area per point (sampling spacing^2), m^2.
    chunk_size : int, optional
        Cloud chunk size for candidate pruning / single-shape JIT.
    """

    def __init__(self, curves, points, minimum_distance, point_weight,
                 half_w=TYPE_KK_OUTER_CHANNEL_HALF_WIDTH_BINORMAL_M,
                 half_d=TYPE_KK_OUTER_CHANNEL_HALF_DEPTH_NORMAL_M,
                 winding_r0=BANANA_WINDING_SURFACE_MAJOR_RADIUS_M,
                 chunk_size=8192):
        self.curves = curves
        self.minimum_distance = float(minimum_distance)
        self.point_weight = float(point_weight)
        self.half_w = float(half_w)
        self.half_d = float(half_d)
        # Fallback winding radius for non-CWS lineages (no embedded surface).
        # ``winding_r0`` stays the public attribute/kwarg for back-compat; the
        # live value is read from the curves' CWS surf each evaluation (B1.3).
        self._winding_r0_fallback = float(winding_r0)
        # The contract distance is centerline corner-reach + safety; the box now
        # carries the corner reach, so the hinge margin is the safety remainder.
        corner_reach = float(np.hypot(half_w, half_d))
        self.margin = self.minimum_distance - corner_reach
        if self.margin <= 0.0:
            raise ValueError(
                f"minimum_distance {minimum_distance} m must exceed the bracket "
                f"corner reach {corner_reach:.4f} m to leave a positive margin")

        pts = np.ascontiguousarray(np.asarray(points, dtype=np.float64))
        if pts.ndim != 2 or pts.shape[1] != 3 or pts.shape[0] == 0:
            raise ValueError(
                f"points must be a non-empty (P, 3) array, got {pts.shape}")
        # Toroidal sort -> spatially coherent chunks -> effective pruning.
        order = np.argsort(np.arctan2(pts[:, 1], pts[:, 0]))
        pts = pts[order]
        pad = (-len(pts)) % chunk_size
        if pad:
            pts = np.vstack([pts, np.full((pad, 3), _PAD_COORDINATE)])
        self._chunks_np = [
            pts[i:i + chunk_size] for i in range(0, len(pts), chunk_size)
        ]
        self._chunks = [jnp.asarray(c) for c in self._chunks_np]
        # Static per-chunk AABBs over the REAL points only (pads excluded so
        # they never widen a chunk's box).
        self._chunk_bounds = []
        for chunk in self._chunks_np:
            real = chunk[np.any(chunk != _PAD_COORDINATE, axis=1)]
            self._chunk_bounds.append((real.min(axis=0), real.max(axis=0)))

        # winding_r0 enters as a CALL-TIME argument (sourced live in J/dJ) so the
        # frame tracks the moving winding surface; it stays in the JAX-traced path
        # (smooth cos/sin/normalize), preserving differentiability. B1.3:
        # value-live; frame-orientation gradient deferred (the curve VJP
        # dgamma_by_dsurf still carries the centerline-translation gradient).
        self.J_jax = jit(lambda gammac, pts_, winding_r0_: hardware_keepout_pure(
            gammac, pts_, self.point_weight, self.half_w, self.half_d,
            self.margin, winding_r0_))
        self.dJ_dgamma = jit(
            lambda gammac, pts_, winding_r0_: grad(self.J_jax, argnums=0)(
                gammac, pts_, winding_r0_))
        self.candidates = None
        super().__init__(depends_on=curves)

    @property
    def winding_r0(self):
        """Fallback winding major radius (constructor value), m.

        Public back-compat attribute. The value the term *scores* against is the
        live :meth:`live_winding_r0`, which equals this for a frozen winding
        surface and for non-CWS lineages.
        """
        return self._winding_r0_fallback

    def live_winding_r0(self):
        """Live winding major radius the frame is currently measured about, m."""
        return live_winding_r0(self.curves, self._winding_r0_fallback)

    def recompute_bell(self, parent=None):
        self.candidates = None

    def compute_candidates(self):
        """(curve, chunk) pairs whose inflated AABBs overlap — a conservative
        superset of pairs with any quadpoint within ``minimum_distance`` of a
        cloud point, so the pruning is exact for the hinge."""
        if self.candidates is None:
            d = self.minimum_distance
            candidates = []
            for i, curve in enumerate(self.curves):
                g = curve.gamma()
                glo, ghi = g.min(axis=0) - d, g.max(axis=0) + d
                for j, (clo, chi) in enumerate(self._chunk_bounds):
                    if np.all(glo <= chi) and np.all(clo <= ghi):
                        candidates.append((i, j))
            self.candidates = candidates

    def shortest_distance(self):
        """Minimum hardware-point-to-U-channel-envelope distance over all
        curves, m (NumPy diagnostic). Negative is impossible here (clamped at
        the box surface); 0 means the metal touches the cloud. Pads sit ~1 km
        away and cannot win the minimum."""
        best = np.inf
        winding_r0 = self.live_winding_r0()
        for curve in self.curves:
            g = np.asarray(curve.gamma(), dtype=np.float64)
            t, gw, gd, hseg = (np.asarray(x) for x in _bracket_frame(
                jnp.asarray(g), winding_r0))
            for chunk in self._chunks_np:
                d = chunk[None, :, :] - g[:, None, :]
                a = np.abs(np.sum(d * t[:, None, :], axis=2))
                b = np.abs(np.sum(d * gw[:, None, :], axis=2))
                c = np.abs(np.sum(d * gd[:, None, :], axis=2))
                da = np.maximum(a - hseg[:, None], 0.0)
                db = np.maximum(b - self.half_w, 0.0)
                dc = np.maximum(c - self.half_d, 0.0)
                box = np.sqrt(da ** 2 + db ** 2 + dc ** 2)
                best = min(best, float(box.min()))
        return best

    # ── Optimizable API ────────────────────────────────────────────────
    def J(self):
        self.compute_candidates()
        winding_r0 = self.live_winding_r0()
        res = 0.0
        for i, j in self.candidates:
            gammac = self.curves[i].gamma()
            res += float(self.J_jax(gammac, self._chunks[j], winding_r0))
        return res

    @derivative_dec
    def dJ(self):
        self.compute_candidates()
        winding_r0 = self.live_winding_r0()
        dgamma_vecs = [np.zeros_like(c.gamma()) for c in self.curves]
        for i, j in self.candidates:
            gammac = self.curves[i].gamma()
            dgamma_vecs[i] += np.asarray(
                self.dJ_dgamma(gammac, self._chunks[j], winding_r0))
        res = [
            self.curves[i].dgamma_by_dcoeff_vjp(dgamma_vecs[i])
            for i in range(len(self.curves))
        ]
        return sum(res)

    return_fn_map = {'J': J, 'dJ': dJ}


class CurveHardwareSdfKeepout(Optimizable):
    r"""
    Optimizer-visible CAD distance-field proxy for static hardware keepout.

    The objective samples the viewer-matched Type KK swept U-channel surface and
    queries one or more manifest-bound hardware distance grids.  It is a
    steering proxy only: ``hardware_contact_report`` remains the direct CAD
    oracle for promotion and handoff.
    """

    def __init__(self, curves, sdf_data,
                 half_w=TYPE_KK_OUTER_CHANNEL_HALF_WIDTH_BINORMAL_M,
                 half_d=TYPE_KK_OUTER_CHANNEL_HALF_DEPTH_NORMAL_M,
                 winding_r0=BANANA_WINDING_SURFACE_MAJOR_RADIUS_M):
        if not isinstance(sdf_data, HardwareSdfData):
            raise TypeError("sdf_data must come from load_hardware_sdf(...)")
        if not sdf_data.groups:
            raise ValueError("hardware SDF payload must contain at least one group")
        self.curves = curves
        self.sdf_data = sdf_data
        self.half_w = float(half_w)
        self.half_d = float(half_d)
        # Fallback winding radius for non-CWS lineages; the live value (read from
        # the curves' CWS surf each evaluation) is what the frame scores against.
        self._winding_r0_fallback = float(winding_r0)
        self._groups = [
            {
                "label": group.label,
                "grid_np": np.ascontiguousarray(group.grid, dtype=np.float64),
                "grid": jnp.asarray(group.grid),
                "origin_np": np.asarray(group.origin_m, dtype=np.float64),
                "origin": jnp.asarray(group.origin_m, dtype=jnp.float64),
                "spacing": float(group.spacing_m),
                "effective_margin": float(group.effective_margin_m),
            }
            for group in sdf_data.groups
        ]
        # winding_r0 is a CALL-TIME argument sourced live in J/dJ (B1.3:
        # value-live; frame-orientation gradient deferred -- the curve VJP keeps
        # the centerline-translation gradient). It stays in the JAX-traced path.
        self.J_jax = jit(
            lambda gammac, grid, origin, spacing, effective_margin, winding_r0_:
            hardware_sdf_keepout_pure(
                gammac,
                grid,
                origin,
                spacing,
                effective_margin,
                self.half_w,
                self.half_d,
                winding_r0_,
            )
        )
        self.dJ_dgamma = jit(
            lambda gammac, grid, origin, spacing, effective_margin, winding_r0_:
            grad(self.J_jax, argnums=0)(
                gammac, grid, origin, spacing, effective_margin, winding_r0_
            )
        )
        super().__init__(depends_on=curves)

    @property
    def winding_r0(self):
        """Fallback winding major radius (constructor value), m. See
        :meth:`live_winding_r0` for the value the term scores against."""
        return self._winding_r0_fallback

    def live_winding_r0(self):
        """Live winding major radius the frame is currently measured about, m."""
        return live_winding_r0(self.curves, self._winding_r0_fallback)

    @property
    def group_labels(self):
        return self.sdf_data.group_labels

    def _group_value(self, gammac, group, winding_r0):
        return float(
            self.J_jax(
                gammac,
                group["grid"],
                group["origin"],
                group["spacing"],
                group["effective_margin"],
                winding_r0,
            )
        )

    def J(self):
        winding_r0 = self.live_winding_r0()
        total = 0.0
        for curve in self.curves:
            gammac = curve.gamma()
            for group in self._groups:
                total += self._group_value(gammac, group, winding_r0)
        return total

    @derivative_dec
    def dJ(self):
        winding_r0 = self.live_winding_r0()
        dgamma_vecs = [np.zeros_like(c.gamma()) for c in self.curves]
        for curve_index, curve in enumerate(self.curves):
            gammac = curve.gamma()
            for group in self._groups:
                dgamma_vecs[curve_index] += np.asarray(
                    self.dJ_dgamma(
                        gammac,
                        group["grid"],
                        group["origin"],
                        group["spacing"],
                        group["effective_margin"],
                        winding_r0,
                    )
                )
        return sum(
            self.curves[i].dgamma_by_dcoeff_vjp(dgamma_vecs[i])
            for i in range(len(self.curves))
        )

    def _interp_numpy(self, grid, origin, spacing, points, outside_value):
        local = (points - origin) / spacing
        shape = np.asarray(grid.shape, dtype=int)
        valid = np.all((local >= 0.0) & (local <= (shape - 1)), axis=1)
        lower_f = np.floor(local)
        lower = np.clip(lower_f.astype(int), 0, shape - 2)
        frac = np.clip(local - lower_f, 0.0, 1.0)
        i0, j0, k0 = lower[:, 0], lower[:, 1], lower[:, 2]
        i1, j1, k1 = i0 + 1, j0 + 1, k0 + 1
        tx, ty, tz = frac[:, 0], frac[:, 1], frac[:, 2]
        c000 = grid[i0, j0, k0]
        c100 = grid[i1, j0, k0]
        c010 = grid[i0, j1, k0]
        c110 = grid[i1, j1, k0]
        c001 = grid[i0, j0, k1]
        c101 = grid[i1, j0, k1]
        c011 = grid[i0, j1, k1]
        c111 = grid[i1, j1, k1]
        c00 = c000 * (1.0 - tx) + c100 * tx
        c10 = c010 * (1.0 - tx) + c110 * tx
        c01 = c001 * (1.0 - tx) + c101 * tx
        c11 = c011 * (1.0 - tx) + c111 * tx
        c0 = c00 * (1.0 - ty) + c10 * ty
        c1 = c01 * (1.0 - ty) + c11 * ty
        value = c0 * (1.0 - tz) + c1 * tz
        return np.where(valid, value, outside_value)

    def per_group_min_clearance(self):
        """Minimum sampled swept-surface SDF value per represented group, m."""
        best = {group["label"]: np.inf for group in self._groups}
        winding_r0 = self.live_winding_r0()
        for curve in self.curves:
            surface_points = np.asarray(
                swept_channel_surface_points(
                    jnp.asarray(curve.gamma()),
                    self.half_w,
                    self.half_d,
                    winding_r0,
                ),
                dtype=np.float64,
            )
            for group in self._groups:
                values = self._interp_numpy(
                    group["grid_np"],
                    group["origin_np"],
                    group["spacing"],
                    surface_points,
                    outside_value=group["effective_margin"],
                )
                best[group["label"]] = min(
                    best[group["label"]], float(values.min())
                )
        return best

    def shortest_distance(self):
        """Minimum sampled swept-surface SDF value, m.

        Negative values indicate the sampled swept surface is inside a signed
        field.  Outside-grid samples use the manifest-guaranteed safe margin.
        The name is retained for the existing results-writer contract;
        ``shortest_clearance`` is an alias for callers that want signed wording.
        """
        return min(self.per_group_min_clearance().values())

    def shortest_clearance(self):
        return self.shortest_distance()

    return_fn_map = {'J': J, 'dJ': dJ}


class CurveHardwareSdfFreeSpaceReward(Optimizable):
    r"""
    Optimizer-visible reward for real CAD/SDF positive hardware clearance.

    The objective samples the same viewer-matched Type KK swept U-channel
    surface as :class:`CurveHardwareSdfKeepout`.  For each manifest hardware
    group it rewards positive signed SDF clearance up to that group's effective
    keepout margin, clips to zero inside hardware, and saturates beyond the
    margin.  The value is bounded in ``[-ncurves * ngroups, 0]`` and remains a
    steering term only; ``hardware_contact_report`` stays the promotion oracle.
    """

    def __init__(self, curves, sdf_data,
                 half_w=TYPE_KK_OUTER_CHANNEL_HALF_WIDTH_BINORMAL_M,
                 half_d=TYPE_KK_OUTER_CHANNEL_HALF_DEPTH_NORMAL_M,
                 winding_r0=BANANA_WINDING_SURFACE_MAJOR_RADIUS_M):
        if not isinstance(sdf_data, HardwareSdfData):
            raise TypeError("sdf_data must come from load_hardware_sdf(...)")
        if not sdf_data.groups:
            raise ValueError("hardware SDF payload must contain at least one group")
        self.curves = curves
        self.sdf_data = sdf_data
        self.half_w = float(half_w)
        self.half_d = float(half_d)
        self._winding_r0_fallback = float(winding_r0)
        self._groups = [
            {
                "grid": jnp.asarray(group.grid),
                "origin": jnp.asarray(group.origin_m, dtype=jnp.float64),
                "spacing": float(group.spacing_m),
                "effective_margin": float(group.effective_margin_m),
            }
            for group in sdf_data.groups
        ]
        self.J_jax = jit(
            lambda gammac, grid, origin, spacing, effective_margin, winding_r0_:
            hardware_sdf_free_space_reward_pure(
                gammac,
                grid,
                origin,
                spacing,
                effective_margin,
                self.half_w,
                self.half_d,
                winding_r0_,
            )
        )
        self.dJ_dgamma = jit(
            lambda gammac, grid, origin, spacing, effective_margin, winding_r0_:
            grad(self.J_jax, argnums=0)(
                gammac, grid, origin, spacing, effective_margin, winding_r0_
            )
        )
        super().__init__(depends_on=curves)

    @property
    def winding_r0(self):
        """Fallback winding major radius (constructor value), m."""
        return self._winding_r0_fallback

    def live_winding_r0(self):
        """Live winding major radius the frame is currently measured about, m."""
        return live_winding_r0(self.curves, self._winding_r0_fallback)

    def J(self):
        winding_r0 = self.live_winding_r0()
        total = 0.0
        for curve in self.curves:
            gammac = curve.gamma()
            for group in self._groups:
                total += float(
                    self.J_jax(
                        gammac,
                        group["grid"],
                        group["origin"],
                        group["spacing"],
                        group["effective_margin"],
                        winding_r0,
                    )
                )
        return total

    @derivative_dec
    def dJ(self):
        winding_r0 = self.live_winding_r0()
        dgamma_vecs = [np.zeros_like(c.gamma()) for c in self.curves]
        for curve_index, curve in enumerate(self.curves):
            gammac = curve.gamma()
            for group in self._groups:
                dgamma_vecs[curve_index] += np.asarray(
                    self.dJ_dgamma(
                        gammac,
                        group["grid"],
                        group["origin"],
                        group["spacing"],
                        group["effective_margin"],
                        winding_r0,
                    )
                )
        return sum(
            self.curves[i].dgamma_by_dcoeff_vjp(dgamma_vecs[i])
            for i in range(len(self.curves))
        )

    return_fn_map = {'J': J, 'dJ': dJ}


class CurveVesselEnvelopeKeepout(Optimizable):
    r"""
    Penalty steering Type KK banana coil envelopes inside the analytic vessel
    torus. It uses the same U-channel frame as :class:`CurveHardwareKeepout`,
    but the obstacle is the fixed vessel ``(R0, a)`` from hardware_contracts.
    """

    def __init__(self, curves,
                 half_w=TYPE_KK_OUTER_CHANNEL_HALF_WIDTH_BINORMAL_M,
                 half_d=TYPE_KK_OUTER_CHANNEL_HALF_DEPTH_NORMAL_M,
                 minimum_clearance=HARDWARE_KEEPOUT_SAFETY_MARGIN_M,
                 winding_r0=BANANA_WINDING_SURFACE_MAJOR_RADIUS_M,
                 vessel_r0=VACUUM_VESSEL_MAJOR_RADIUS_M,
                 vessel_minor_radius=VACUUM_VESSEL_MINOR_RADIUS_M):
        self.curves = curves
        self.half_w = float(half_w)
        self.half_d = float(half_d)
        self.minimum_clearance = float(minimum_clearance)
        # Fallback winding radius for non-CWS lineages; the live value (read from
        # the curves' CWS surf each evaluation) is what the frame scores against.
        self._winding_r0_fallback = float(winding_r0)
        self.vessel_r0 = float(vessel_r0)
        self.vessel_minor_radius = float(vessel_minor_radius)
        # winding_r0 is a CALL-TIME argument sourced live in J/dJ (B1.3:
        # value-live; frame-orientation gradient deferred -- the curve VJP keeps
        # the centerline-translation gradient). It stays in the JAX-traced path.
        self.J_jax = jit(lambda gammac, winding_r0_: vessel_envelope_keepout_pure(
            gammac,
            self.half_w,
            self.half_d,
            self.minimum_clearance,
            winding_r0_,
            self.vessel_r0,
            self.vessel_minor_radius,
        ))
        self.dJ_dgamma = jit(
            lambda gammac, winding_r0_: grad(self.J_jax, argnums=0)(
                gammac, winding_r0_))
        super().__init__(depends_on=curves)

    @property
    def winding_r0(self):
        """Fallback winding major radius (constructor value), m. See
        :meth:`live_winding_r0` for the value the term scores against."""
        return self._winding_r0_fallback

    def live_winding_r0(self):
        """Live winding major radius the frame is currently measured about, m."""
        return live_winding_r0(self.curves, self._winding_r0_fallback)

    def shortest_clearance(self):
        """Minimum signed Type KK envelope clearance to the vessel, m."""
        best = np.inf
        winding_r0 = self.live_winding_r0()
        for curve in self.curves:
            clearance = vessel_envelope_clearance_pure(
                jnp.asarray(curve.gamma()),
                self.half_w,
                self.half_d,
                winding_r0,
                self.vessel_r0,
                self.vessel_minor_radius,
            )
            best = min(best, float(clearance))
        return best

    def J(self):
        winding_r0 = self.live_winding_r0()
        return sum(
            float(self.J_jax(curve.gamma(), winding_r0)) for curve in self.curves
        )

    @derivative_dec
    def dJ(self):
        winding_r0 = self.live_winding_r0()
        return sum(
            curve.dgamma_by_dcoeff_vjp(
                np.asarray(self.dJ_dgamma(curve.gamma(), winding_r0))
            )
            for curve in self.curves
        )

    return_fn_map = {'J': J, 'dJ': dJ}


class CurveVesselAvailableEnvelopeReward(Optimizable):
    r"""
    Smooth reward for moving Type KK envelopes into usable vessel volume.

    The value is bounded in ``[-ncurves, 0]`` and clips at the required positive
    clearance, so it rewards filling available analytic vessel envelope space
    without creating a reward for crossing the keep-out boundary.  It is only a
    steering term; the direct CAD contact oracle and confinement gates remain
    the promotion criteria.
    """

    def __init__(self, curves,
                 half_w=TYPE_KK_OUTER_CHANNEL_HALF_WIDTH_BINORMAL_M,
                 half_d=TYPE_KK_OUTER_CHANNEL_HALF_DEPTH_NORMAL_M,
                 minimum_clearance=HARDWARE_KEEPOUT_SAFETY_MARGIN_M,
                 winding_r0=BANANA_WINDING_SURFACE_MAJOR_RADIUS_M,
                 vessel_r0=VACUUM_VESSEL_MAJOR_RADIUS_M,
                 vessel_minor_radius=VACUUM_VESSEL_MINOR_RADIUS_M):
        self.curves = curves
        self.half_w = float(half_w)
        self.half_d = float(half_d)
        self.minimum_clearance = float(minimum_clearance)
        self._winding_r0_fallback = float(winding_r0)
        self.vessel_r0 = float(vessel_r0)
        self.vessel_minor_radius = float(vessel_minor_radius)
        self.J_jax = jit(
            lambda gammac, winding_r0_: vessel_available_envelope_reward_pure(
                gammac,
                self.half_w,
                self.half_d,
                self.minimum_clearance,
                winding_r0_,
                self.vessel_r0,
                self.vessel_minor_radius,
            )
        )
        self.dJ_dgamma = jit(
            lambda gammac, winding_r0_: grad(self.J_jax, argnums=0)(
                gammac, winding_r0_))
        super().__init__(depends_on=curves)

    @property
    def winding_r0(self):
        """Fallback winding major radius (constructor value), m."""
        return self._winding_r0_fallback

    def live_winding_r0(self):
        """Live winding major radius the frame is currently measured about, m."""
        return live_winding_r0(self.curves, self._winding_r0_fallback)

    def J(self):
        winding_r0 = self.live_winding_r0()
        return sum(
            float(self.J_jax(curve.gamma(), winding_r0)) for curve in self.curves
        )

    @derivative_dec
    def dJ(self):
        winding_r0 = self.live_winding_r0()
        return sum(
            curve.dgamma_by_dcoeff_vjp(
                np.asarray(self.dJ_dgamma(curve.gamma(), winding_r0))
            )
            for curve in self.curves
        )

    return_fn_map = {'J': J, 'dJ': dJ}


def _sha256_file(path):
    """Stream ``path`` through SHA-256 (constant memory) and return the hex
    digest, matching the exporter's ``hashlib.sha256(...).hexdigest()``."""
    digest = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


EFFECTIVE_KEEPOUT_GROUPS_KEY = "EFFECTIVE_KEEPOUT_GROUPS"
OPTIMIZER_SAFE_HARDWARE_SDF_SIGN_METHODS = frozenset({
    "component_union_watertight_contains_trimesh_nearest",
    "watertight_contains_trimesh_nearest",
})
HARDWARE_SDF_ERROR_BUDGET_COMPONENT_KEYS = (
    "e_sweep_sample_m",
    "e_grid_m",
    "e_sign_m",
    "e_mesh_m",
    "e_oracle_mapping_m",
)


def _read_hardware_keepout_data(path):
    with open(path) as f:
        data = json.load(f)
    if data.get("schema_version") != 1:
        raise ValueError(
            f"unsupported keepout schema_version {data.get('schema_version')!r}")
    if data.get("frame") != "machine_metres_zup" or data.get("units") != "m":
        raise ValueError(
            f"keepout frame/units mismatch: {data.get('frame')!r}/"
            f"{data.get('units')!r}; expected machine_metres_zup metres "
            f"(the coils' frame)")
    return data


def _validated_live_glb_sha(data, path, glb_path):
    if glb_path is None:
        return None
    provenance = data["provenance"]
    recorded_sha = provenance.get("glb_sha256")
    live_sha = _sha256_file(glb_path)
    if recorded_sha != live_sha:
        raise ValueError(
            f"stale hardware keep-out cloud {os.fspath(path)!r}: its "
            f"provenance.glb_sha256 {recorded_sha!r} (sampled from a prior "
            f"GLB) does not match the live GLB {os.fspath(glb_path)!r} "
            f"sha256 {live_sha!r}; regenerate the cloud from the live GLB "
            f"before steering against it (fail-closed)")
    return live_sha


def hardware_keepout_metadata(path, glb_path=None):
    """Return run-stamp metadata for the exported hardware keep-out cloud.

    This shares the loader's schema/frame/freshness gates so producers cannot
    stamp a cloud that they would not be allowed to steer against.
    """
    data = _read_hardware_keepout_data(path)
    live_sha = _validated_live_glb_sha(data, path, glb_path)
    provenance = data["provenance"]
    return {
        "HARDWARE_KEEPOUT_BACKEND": "point_cloud",
        "HARDWARE_KEEPOUT_JSON": os.fspath(path),
        "HARDWARE_KEEPOUT_JSON_SHA256": _sha256_file(path),
        "HARDWARE_KEEPOUT_GROUPS": [
            str(group["label"]) for group in data["groups"]
        ],
        "DOCUMENTED_GATE_ONLY_GROUPS": sorted(
            str(key) for key in data.get("excluded", {}) if str(key) != "vessel"
        ),
        "HARDWARE_KEEPOUT_PROVENANCE_GLB": provenance.get("glb"),
        "HARDWARE_KEEPOUT_PROVENANCE_GLB_SHA256": provenance.get("glb_sha256"),
        "HARDWARE_KEEPOUT_LIVE_GLB": (
            None if glb_path is None else os.fspath(glb_path)
        ),
        "HARDWARE_KEEPOUT_LIVE_GLB_SHA256": live_sha,
    }


def effective_keepout_groups(hardware_group_labels, *, vessel_active):
    """Canonical producer-side group list consumed by contact audits."""
    groups = []
    if vessel_active:
        groups.append("vessel")
    for label in hardware_group_labels:
        label = str(label)
        if label not in groups:
            groups.append(label)
    return groups


def hardware_keepout_results_fields(
    *, hardware_group_labels, vessel_active, metadata=None
):
    fields = {
        EFFECTIVE_KEEPOUT_GROUPS_KEY: effective_keepout_groups(
            hardware_group_labels,
            vessel_active=vessel_active,
        )
    }
    if metadata is not None:
        fields.update(metadata)
    return fields


def load_hardware_keepout(path, glb_path=None):
    """Load a ``hardware_keepout.json`` produced by
    ``hbt_clearance_viewer/tools/export_hardware_keepout.py``.

    Returns ``(points, point_weight, recommended_min_distance, provenance)``
    where ``points`` is the concatenated (P, 3) float64 cloud over all
    groups, ``point_weight`` the per-point surface patch area (spacing^2,
    m^2), ``recommended_min_distance`` the centerline threshold recorded by
    the exporter, and ``provenance`` the raw provenance block.

    Parameters
    ----------
    glb_path : str | os.PathLike | None, optional
        When provided, the cloud is freshness-checked against the live GLB:
        ``sha256(glb_path)`` (streamed) must equal the cloud's recorded
        ``provenance["glb_sha256"]``, else a :class:`ValueError` is raised
        (fail-closed) so a run never steers against stale geometry. The
        default ``None`` preserves the historical behaviour (no sha check).
    """
    data = _read_hardware_keepout_data(path)
    provenance = data["provenance"]
    _validated_live_glb_sha(data, path, glb_path)
    points = np.concatenate(
        [np.asarray(group["points"], dtype=np.float64) for group in data["groups"]],
        axis=0,
    )
    spacing = float(data["spacing_m"])
    return (
        points,
        spacing * spacing,
        float(data["recommended_min_distance_m"]),
        provenance,
    )


def _read_hardware_sdf_manifest(path):
    with open(path) as f:
        data = json.load(f)
    if data.get("schema_version") != 1:
        raise ValueError(
            f"unsupported SDF schema_version {data.get('schema_version')!r}")
    if data.get("kind") not in {None, "hardware_sdf"}:
        raise ValueError(f"unsupported SDF kind {data.get('kind')!r}")
    if data.get("frame") != "machine_metres_zup" or data.get("units") != "m":
        raise ValueError(
            f"SDF frame/units mismatch: {data.get('frame')!r}/"
            f"{data.get('units')!r}; expected machine_metres_zup metres")
    return data


def _resolve_manifest_relative(manifest_path, payload_path):
    payload = Path(os.fspath(payload_path))
    if payload.is_absolute():
        return payload
    return Path(os.fspath(manifest_path)).resolve().parent / payload


def _coverage_keys(payload):
    if isinstance(payload, dict):
        return set(str(key) for key in payload)
    return set(str(key) for key in payload)


def validate_hardware_sdf_static_coverage(
    *,
    represented_groups,
    documented_gate_only,
    static_hardware_keys,
    covered_by_other_in_loop=(),
):
    """Fail closed unless every oracle static key is covered or documented."""
    represented = _coverage_keys(represented_groups)
    gate_only = _coverage_keys(documented_gate_only)
    other_in_loop = _coverage_keys(covered_by_other_in_loop)
    static = _coverage_keys(static_hardware_keys)
    missing = sorted(static - represented - gate_only - other_in_loop)
    if missing:
        raise ValueError(
            "hardware SDF manifest does not cover static hardware groups "
            f"{missing}; add represented fields or document them as gate-only")


def _validate_hardware_sdf_error_budget(manifest):
    budget = manifest.get("error_budget_m")
    if not isinstance(budget, dict):
        raise ValueError("hardware SDF manifest must declare error_budget_m")
    components = {}
    for key in HARDWARE_SDF_ERROR_BUDGET_COMPONENT_KEYS:
        try:
            value = float(budget[key])
        except KeyError as exc:
            raise ValueError(
                f"hardware SDF error_budget_m is missing {key!r}") from exc
        if not np.isfinite(value) or value < 0.0:
            raise ValueError(
                f"hardware SDF error budget {key} must be finite and >= 0")
        components[key] = value
    computed_total = sum(components.values())
    recorded_total = float(budget.get("e_total_m", -1.0))
    if not np.isfinite(recorded_total):
        raise ValueError("hardware SDF error_budget_m.e_total_m must be finite")
    if not np.isclose(recorded_total, computed_total, rtol=0.0, atol=1.0e-12):
        raise ValueError(
            "hardware SDF error_budget_m.e_total_m must equal the sum of its "
            f"components ({recorded_total} vs {computed_total})")
    safety_margin = float(manifest.get("safety_margin_m", -1.0))
    if not np.isfinite(safety_margin) or safety_margin <= 0.0:
        raise ValueError(
            "hardware SDF manifest safety_margin_m must be finite and > 0")
    effective_margin = float(manifest.get("effective_margin_m", -1.0))
    if not np.isfinite(effective_margin):
        raise ValueError(
            "hardware SDF manifest effective_margin_m must be finite")
    minimum_effective = safety_margin + recorded_total
    if effective_margin + 1.0e-12 < minimum_effective:
        raise ValueError(
            "hardware SDF effective_margin_m must cover safety_margin_m plus "
            f"error_budget_m.e_total_m ({effective_margin} < "
            f"{minimum_effective})")
    components["e_total_m"] = recorded_total
    return safety_margin, components, minimum_effective


def _validate_hardware_sdf_narrow_band(narrow_band, effective_margin, label):
    if not np.isfinite(narrow_band) or narrow_band <= 0.0:
        raise ValueError(
            f"SDF {label} narrow_band_m must be finite and > 0")
    if narrow_band + 1.0e-12 < effective_margin:
        raise ValueError(
            f"SDF {label} narrow_band_m must cover effective_margin_m "
            f"({narrow_band} < {effective_margin})")


def _validated_hardware_sdf_glb_sha(manifest, path, glb_path):
    if glb_path is None:
        return None
    provenance = manifest.get("provenance", {})
    recorded_sha = provenance.get("glb_sha256")
    live_sha = _sha256_file(glb_path)
    if recorded_sha != live_sha:
        raise ValueError(
            f"stale hardware SDF manifest {os.fspath(path)!r}: its "
            f"provenance.glb_sha256 {recorded_sha!r} does not match live GLB "
            f"{os.fspath(glb_path)!r} sha256 {live_sha!r}; regenerate the SDF "
            "from the live GLB before steering against it (fail-closed)")
    return live_sha


def load_hardware_sdf(path, glb_path=None):
    """Load a manifest-bound ``hardware_sdf.json``/``.npz`` payload.

    The manifest must use the machine metre frame, sha-bind its data payload,
    declare the oracle static hardware key set, and either represent each key
    or declare the key under documented gate-only/other-in-loop coverage.  The
    returned object is accepted directly by :class:`CurveHardwareSdfKeepout`.
    """
    manifest_path = Path(os.fspath(path))
    manifest = _read_hardware_sdf_manifest(manifest_path)
    live_glb_sha = _validated_hardware_sdf_glb_sha(manifest, manifest_path, glb_path)
    data_path = _resolve_manifest_relative(
        manifest_path, manifest.get("data_file", "hardware_sdf.npz")
    )
    manifest_sha = _sha256_file(manifest_path)
    data_sha = _sha256_file(data_path)
    recorded_data_sha = manifest.get("data_sha256")
    if not recorded_data_sha:
        raise ValueError("hardware SDF manifest must sha-bind data_sha256")
    if recorded_data_sha != data_sha:
        raise ValueError(
            f"stale hardware SDF data {os.fspath(data_path)!r}: manifest records "
            f"data_sha256 {recorded_data_sha!r}, live file is {data_sha!r}")
    safety_margin, error_budget, minimum_effective_margin = (
        _validate_hardware_sdf_error_budget(manifest)
    )

    documented_gate_only = dict(manifest.get("documented_gate_only", {}))
    covered_by_other_in_loop = dict(manifest.get("covered_by_other_in_loop", {}))
    group_specs = tuple(manifest.get("groups", ()))
    if not group_specs:
        raise ValueError("hardware SDF manifest must contain at least one group")
    represented = [str(group["label"]) for group in group_specs]
    static_keys = manifest.get("static_hardware_keys")
    if not static_keys:
        raise ValueError(
            "hardware SDF manifest must declare non-empty static_hardware_keys")
    validate_hardware_sdf_static_coverage(
        represented_groups=represented,
        documented_gate_only=documented_gate_only,
        covered_by_other_in_loop=covered_by_other_in_loop,
        static_hardware_keys=static_keys,
    )

    top_margin = float(manifest.get("effective_margin_m"))
    top_narrow_band = float(manifest.get("narrow_band_m", -1.0))
    _validate_hardware_sdf_narrow_band(
        top_narrow_band, top_margin, "manifest")
    groups = []
    with np.load(data_path) as payload:
        for group in group_specs:
            label = str(group["label"])
            field_key = str(group.get("field_key", label))
            if field_key not in payload:
                raise ValueError(
                    f"SDF data payload {os.fspath(data_path)!r} is missing "
                    f"field {field_key!r} for group {label!r}")
            grid = np.ascontiguousarray(np.asarray(payload[field_key], dtype=np.float64))
            if grid.ndim != 3 or min(grid.shape) < 2:
                raise ValueError(
                    f"SDF group {label!r} must be a 3-D grid with every "
                    f"dimension >= 2, got {grid.shape}")
            if not np.isfinite(grid).all():
                raise ValueError(
                    f"SDF group {label!r} grid values must be finite")
            expected_shape = group.get("shape")
            if expected_shape is not None and tuple(expected_shape) != grid.shape:
                raise ValueError(
                    f"SDF group {label!r} shape mismatch: manifest "
                    f"{tuple(expected_shape)} vs payload {grid.shape}")
            origin = np.asarray(group["origin_m"], dtype=np.float64)
            if origin.shape != (3,):
                raise ValueError(
                    f"SDF group {label!r} origin_m must be length 3, got "
                    f"{origin.shape}")
            if not np.isfinite(origin).all():
                raise ValueError(
                    f"SDF group {label!r} origin_m values must be finite")
            spacing = float(group["spacing_m"])
            if not np.isfinite(spacing) or spacing <= 0.0:
                raise ValueError(
                    f"SDF group {label!r} spacing_m must be finite and > 0")
            effective_margin = float(group.get("effective_margin_m", top_margin))
            if not np.isfinite(effective_margin) or effective_margin <= 0.0:
                raise ValueError(
                    f"SDF group {label!r} effective_margin_m must be finite "
                    "and > 0")
            if effective_margin + 1.0e-12 < minimum_effective_margin:
                raise ValueError(
                    f"SDF group {label!r} effective_margin_m must cover "
                    "safety_margin_m plus error_budget_m.e_total_m "
                    f"({effective_margin} < {minimum_effective_margin})")
            narrow_band = float(group.get("narrow_band_m", top_narrow_band))
            _validate_hardware_sdf_narrow_band(
                narrow_band, effective_margin, f"group {label!r}")
            sign_method = str(group.get("sign_method", "unknown"))
            if sign_method not in OPTIMIZER_SAFE_HARDWARE_SDF_SIGN_METHODS:
                allowed = ", ".join(sorted(
                    OPTIMIZER_SAFE_HARDWARE_SDF_SIGN_METHODS))
                raise ValueError(
                    f"SDF group {label!r} sign_method {sign_method!r} is not "
                    f"optimizer-safe; expected one of {allowed}")
            groups.append(
                HardwareSdfGroup(
                    label=label,
                    grid=grid,
                    origin_m=origin,
                    spacing_m=spacing,
                    narrow_band_m=narrow_band,
                    effective_margin_m=effective_margin,
                    sign_method=sign_method,
                )
            )

    provenance = dict(manifest.get("provenance", {}))
    if live_glb_sha is not None:
        provenance["live_glb_sha256"] = live_glb_sha
        provenance["live_glb"] = os.fspath(glb_path)
    return HardwareSdfData(
        manifest_path=os.fspath(manifest_path),
        data_path=os.fspath(data_path),
        manifest_sha256=manifest_sha,
        data_sha256=data_sha,
        groups=tuple(groups),
        safety_margin_m=safety_margin,
        error_budget_m=error_budget,
        documented_gate_only=documented_gate_only,
        covered_by_other_in_loop=covered_by_other_in_loop,
        provenance=provenance,
    )


def hardware_sdf_metadata_from_data(sdf_data):
    """Return run-stamp metadata for a loaded SDF hardware keepout payload."""
    provenance = sdf_data.provenance
    return {
        "HARDWARE_KEEPOUT_BACKEND": "sdf",
        "HARDWARE_SDF_MANIFEST": sdf_data.manifest_path,
        "HARDWARE_SDF_MANIFEST_SHA256": sdf_data.manifest_sha256,
        "HARDWARE_SDF_DATA": sdf_data.data_path,
        "HARDWARE_SDF_SHA256": sdf_data.data_sha256,
        "HARDWARE_SDF_GROUPS": list(sdf_data.group_labels),
        "HARDWARE_SDF_SIGN_METHODS": sdf_data.sign_methods,
        "HARDWARE_SDF_EFFECTIVE_MARGIN_M": sdf_data.effective_margin_m,
        "HARDWARE_SDF_SAFETY_MARGIN_M": sdf_data.safety_margin_m,
        "HARDWARE_SDF_ERROR_BUDGET_M": sdf_data.error_budget_m,
        "DOCUMENTED_GATE_ONLY_GROUPS": sorted(
            str(key) for key in sdf_data.documented_gate_only
        ),
        "HARDWARE_SDF_OTHER_IN_LOOP_GROUPS": sorted(
            str(key) for key in sdf_data.covered_by_other_in_loop
        ),
        "HARDWARE_SDF_PROVENANCE_GLB": provenance.get("glb"),
        "HARDWARE_SDF_PROVENANCE_GLB_SHA256": provenance.get("glb_sha256"),
        "HARDWARE_SDF_LIVE_GLB": provenance.get("live_glb"),
        "HARDWARE_SDF_LIVE_GLB_SHA256": provenance.get("live_glb_sha256"),
    }


def hardware_sdf_metadata(path, glb_path=None):
    """Return run-stamp metadata for an SDF hardware keepout payload."""
    return hardware_sdf_metadata_from_data(
        load_hardware_sdf(path, glb_path=glb_path)
    )
