"""Stable public backend facade that forwards to the backend package home."""

import os
from pathlib import Path

_BACKEND_PACKAGE_DIR = Path(__file__).with_suffix("")

__path__ = [str(_BACKEND_PACKAGE_DIR)]

from simsopt.backend.runtime import (  # noqa: E402
    VALID_BACKEND_MODES,
    BackendConfig,
    ChunkTuning,
    FieldKernelTuning,
    BackendPolicy,
    apply_jax_runtime_config,
    get_backend,
    get_backend_config,
    get_backend_mode,
    get_backend_policy,
    get_chunk_policy,
    get_chunk_tuning,
    get_coil_chunk_size,
    get_compilation_cache_dir,
    get_compilation_cache_policy,
    get_debug_nans,
    get_field_kernel_tuning,
    get_jax_platform,
    get_pairwise_penalty_chunk_size,
    get_point_chunk_size,
    get_provenance_label,
    get_quadrature_block_size,
    get_tolerance_tier,
    get_transfer_guard,
    invalidate_backend_cache,
    is_backend_strict,
    is_jax_backend,
    is_parity_mode,
    raise_if_strict_jax_fallback,
    requires_x64,
    set_backend,
    should_eagerly_configure_jax,
    warn_if_jax_fallback,
)

__all__ = (
    "VALID_BACKEND_MODES",
    "BackendConfig",
    "ChunkTuning",
    "FieldKernelTuning",
    "BackendPolicy",
    "apply_jax_runtime_config",
    "get_backend",
    "get_backend_config",
    "get_backend_mode",
    "get_backend_policy",
    "get_chunk_policy",
    "get_chunk_tuning",
    "get_coil_chunk_size",
    "get_compilation_cache_dir",
    "get_compilation_cache_policy",
    "get_debug_nans",
    "get_field_kernel_tuning",
    "get_jax_platform",
    "get_pairwise_penalty_chunk_size",
    "get_point_chunk_size",
    "get_provenance_label",
    "get_quadrature_block_size",
    "get_tolerance_tier",
    "get_transfer_guard",
    "invalidate_backend_cache",
    "is_backend_strict",
    "is_jax_backend",
    "is_parity_mode",
    "raise_if_strict_jax_fallback",
    "requires_x64",
    "set_backend",
    "should_eagerly_configure_jax",
    "warn_if_jax_fallback",
    # Keep ``os`` available on the facade for existing tests/helpers.
    "os",
)
