"""Public runtime configuration helpers for simsopt."""

from __future__ import annotations

from .backend import (
    BackendConfig,
    BackendPolicy,
    ChunkTuning,
    ShardingTuning,
    VALID_BACKEND_MODES,
    apply_jax_runtime_config,
    get_backend,
    get_backend_config,
    get_backend_mode,
    get_backend_policy,
    get_chunk_policy,
    get_chunk_tuning,
    get_compilation_cache_dir,
    get_compilation_cache_policy,
    get_debug_nans,
    get_jax_platform,
    get_pairwise_penalty_chunk_size,
    get_point_chunk_size,
    get_provenance_label,
    get_sharding_strategy,
    get_sharding_tuning,
    get_tolerance_tier,
    get_transfer_guard,
    is_backend_strict,
    is_jax_backend,
    is_parity_mode,
    should_shard_points,
    requires_x64,
    set_backend,
)

__all__ = [
    "BackendConfig",
    "BackendPolicy",
    "ChunkTuning",
    "ShardingTuning",
    "VALID_BACKEND_MODES",
    "apply_jax_runtime_config",
    "get_backend",
    "get_backend_config",
    "get_backend_mode",
    "get_backend_policy",
    "get_chunk_policy",
    "get_chunk_tuning",
    "get_compilation_cache_dir",
    "get_compilation_cache_policy",
    "get_debug_nans",
    "get_jax_platform",
    "get_pairwise_penalty_chunk_size",
    "get_point_chunk_size",
    "get_provenance_label",
    "get_sharding_strategy",
    "get_sharding_tuning",
    "get_tolerance_tier",
    "get_transfer_guard",
    "is_backend_strict",
    "is_jax_backend",
    "is_parity_mode",
    "should_shard_points",
    "requires_x64",
    "set_backend",
]
