# coding: utf-8
# Copyright (c) HiddenSymmetries Development Team.
# Distributed under the terms of the MIT License

"""
Provides json emitting and parsing functionality that can handle graphs.
A majority of the code is based on monty.json.
Credits: Materials Virtual Job
"""

import datetime
import json
import os
import pathlib
import types
from collections import defaultdict
from dataclasses import fields, is_dataclass
from enum import Enum
from importlib import import_module
from inspect import getfullargspec
from math import cos, sin
from typing import NamedTuple
from uuid import UUID

import numpy as np

try:
    import jax
except ImportError:
    jax = None

try:
    import pandas as pd
except ImportError:
    pd = None  # type: ignore

try:
    import bson
except ImportError:
    bson = None  # type: ignore

try:
    from ruamel.yaml import YAML
except ImportError:
    YAML = None  # type: ignore

try:
    import orjson
except ImportError:
    orjson = None  # type: ignore

__version__ = "3.0.0"


_SIMSON_MODULE = "simsopt._core.json"
_SIMSON_CLASS = "SIMSON"
_SPEC_MODULE = "simsopt.jax_core.specs"


class _CurvePayload(NamedTuple):
    curve: object
    rotmat: object


class _CurrentPayload(NamedTuple):
    current: object
    scale: float


def _load_redirect(redirect_file):
    try:
        with open(redirect_file) as f:
            yaml = YAML()
            d = yaml.load(f)
    except OSError:
        # If we can't find the file
        # Just use an empty redirect dict
        return {}

    # Convert the full paths to module/class
    redirect_dict = defaultdict(dict)
    for old_path, new_path in d.items():
        old_class = old_path.split(".")[-1]
        old_module = ".".join(old_path.split(".")[:-1])

        new_class = new_path.split(".")[-1]
        new_module = ".".join(new_path.split(".")[:-1])

        redirect_dict[old_module][old_class] = {
            "@module": new_module,
            "@class": new_class,
        }

    return dict(redirect_dict)


class GSONable:
    """
    This is a mix-in base class specifying an API for GSONable objects. GSON
    is Graph JSON. This class aims to overcome the limitation of JSON in
    serializing/deserializing of objects whose compositional pattern resembles
    a direct acyclic graph (DAG). Essentially, GSONable objects must implement an as_dict
    method, which must return a json serializable dict and also a unique path
    within the json document plus a unique identifier,
    and a from_dict class method that regenerates the object from the dict
    generated by the as_dict method. The as_dict method should contain the
    "@module", "@class", and "@name" keys which will allow the GSONEncoder to
    dynamically deserialize the class. E.g.::
        d["@module"] = self.__class__.__module__
        d["@class"] = self.__class__.__name__
        d["@name"] = self.name
    The "@name" should provide a unique id to represent the instance.
    A default implementation is provided in GSONable, which automatically
    determines if the class already contains self.argname or self._argname
    attributes for every arg. If so, these will be used for serialization in
    the dict format. Similarly, the default from_dict will deserialization
    classes of such form. An example is given below::
        class GSONClass(GSONable):
        def __init__(self, a, b, c, d=1, **kwargs):
            self.a = a
            self.b = b
            self._c = c
            self._d = d
            self.kwargs = kwargs
    For such classes, you merely need to inherit from GSONable and you do not
    need to implement your own as_dict or from_dict protocol.
    GSONable objects need to have a `name` attribute that is unique.
    Classes can be redirected to moved implementations by putting in the old
    fully qualified path and new fully qualified path into .simsopt.yaml in the
    home folder
    Example:
    old_module.old_class: new_module.new_class
    """

    REDIRECT = _load_redirect(
        os.path.join(os.path.expanduser("~"), ".simsopt.yaml"))

    def as_dict(self, serial_objs_dict):
        """
        A JSON serializable dict representation of an object.
        """
        name = getattr(self, "name", str(id(self)))
        d = {"@module": self.__class__.__module__,
             "@class": self.__class__.__name__,
             "@name": name}

        try:
            parent_module = \
                self.__class__.__module__.split(".", maxsplit=1)[0]
            module_version = import_module(
                parent_module).__version__  # type: ignore
            d["@version"] = str(module_version)
        except (AttributeError, ImportError):
            d["@version"] = None  # type: ignore

        spec = getfullargspec(self.__class__.__init__)
        args = spec.args

        def recursive_as_dict(obj):
            if isinstance(obj, (list, tuple)):
                return [recursive_as_dict(it) for it in obj]
            if isinstance(obj, dict):
                return {kk: recursive_as_dict(vv) for kk, vv in obj.items()}
            if callable(obj) and not isinstance(obj, GSONable):
                return _serialize_callable(obj, serial_objs_dict=serial_objs_dict)
            if hasattr(obj, "as_dict"):
                name = getattr(obj, "name", str(id(obj)))
                if name not in serial_objs_dict:  # Add the path
                    serial_obj = obj.as_dict(serial_objs_dict)  # serial_objs is modified in place
                    serial_objs_dict[name] = serial_obj
                return {"$type": "ref", "value": name}
            return obj

        for c in args:
            if c != "self":
                try:
                    a = getattr(self, c)
                except AttributeError:
                    try:
                        a = getattr(self, "_" + c)
                    except AttributeError:
                        print(f"Missing attribute is {c}")
                        raise NotImplementedError(
                            "Unable to automatically determine as_dict "
                            "format from class. GSONAble requires all "
                            "args to be present as either self.argname or "
                            "self._argname, and kwargs to be present under"
                            "a self.kwargs variable to automatically "
                            "determine the dict format. Alternatively, "
                            "you can implement both as_dict and from_dict."
                        )
                d[c] = recursive_as_dict(a)
        if hasattr(self, "kwargs"):
            # type: ignore
            d.update(**getattr(self, "kwargs"))  # pylint: disable=E1101
        if spec.varargs is not None and getattr(self, spec.varargs,
                                                None) is not None:
            d.update({spec.varargs: getattr(self, spec.varargs)})
        if hasattr(self, "_kwargs"):
            d.update(**getattr(self, "_kwargs"))  # pylint: disable=E1101
        if isinstance(self, Enum):
            d.update({"value": self.value})  # pylint: disable=E1101
        return d  # , serial_objs_dict

    def as_dict2(self, serial_objs_dict):
        """
        This is a slightly modified version of as_dict method to deal with the cases
        where the supplied object itself needs to be added to serial_objs_dict.
        """
        def recursive_as_dict(obj):
            if isinstance(obj, (list, tuple)):
                return [recursive_as_dict(it) for it in obj]
            if isinstance(obj, dict):
                return {kk: recursive_as_dict(vv) for kk, vv in obj.items()}
            if callable(obj) and not isinstance(obj, GSONable):
                return _serialize_callable(obj, serial_objs_dict=serial_objs_dict)
            if hasattr(obj, "as_dict"):
                name = getattr(obj, "name", str(id(obj)))
                if name not in serial_objs_dict:  # Add the path
                    serial_obj = obj.as_dict(serial_objs_dict)  # serial_objs is modified in place
                    serial_objs_dict[name] = serial_obj
                return {"$type": "ref", "value": name}
            return obj

        return recursive_as_dict(self)

    @classmethod
    def from_dict(cls, d, serial_objs_dict, recon_objs):
        """
        :param d: Dict representation.
        :return: GSONable class.
        """
        decoded = {k: GSONDecoder().process_decoded(v, serial_objs_dict, recon_objs) for k, v in
                   d.items() if not k.startswith("@")}
        return cls(**decoded)

    def to_json(self) -> str:
        """
        Returns a json string representation of the GSONable object.
        """
        return json.dumps(SIMSON(self), cls=GSONEncoder)

    @classmethod
    def __get_validators__(cls):
        """Return validators for use in pydantic"""
        yield cls.validate_gson

    @classmethod
    def validate_gson(cls, v):
        """
        pydantic Validator for GSONable pattern
        """
        if isinstance(v, cls):
            return v
        if isinstance(v, dict):
            new_obj = GSONDecoder().process_decoded(v)
            if isinstance(new_obj, cls):
                return new_obj

            new_obj = cls(**v)
            return new_obj

        raise ValueError(
            f"Must provide {cls.__name__}, the as_dict form, or the proper")

    @classmethod
    def __modify_schema__(cls, field_schema):
        """JSON schema for GSONable pattern"""
        field_schema.update(
            {
                "type": "object",
                "properties": {
                    "@class": {"enum": [cls.__name__], "type": "string"},
                    "@module": {"enum": [cls.__module__], "type": "string"},
                    "@version": {"type": "string"},
                },
                "required": ["@class", "@module"],
            }
        )


class SIMSON:
    """
    Wrapper class providing a scaffolding for serializing the graph
    framework implemented in simsopt. This class aims to overcome the
    limitation of JSON in serializing/deserializing of objects whose
    compositional pattern resembles a direct acyclic graph (DAG). This
    class is used to wrap the simsopt graph just before passing the simsopt
    graph to serializing functions. Essentially, SIMSON generates an extra
    dictionary that contains only serialized GSONable objects and the
    conventionally generated JSON doc contains only references (by the way of
    keys in the extra dictionary) for serialized GSONable objects.
    Only one instance should be used to enclose the entire graph.
    This class implements an as_dict method, which returns a json serializable
    dict with two subdicts with keys: "graph" and "simsopt_objs". The "graph"
    subdict consists of the json doc typically produced where all simsopt objs
    replaced by their references in the "simsopt_objs" subdict. "simsopt_objs"
    is a dict whose keys are the unique identifiers for simsopt objects and
    the values are the serialized simsopt objects.
    For deserialization a from_dict class method is implemented that
    regenerates the object from the dicts
    generated by the as_dict method. The as_dict method should contain the
    "@module" and "@class" keys which will allow the GSONEncoder to
    dynamically deserialize the class. E.g.::
        d["@module"] = self.__class__.__module__
        d["@class"] = self.__class__.__name__
    """

    def __init__(self, simsopt_objs):
        self.simsopt_objs = simsopt_objs

    def as_dict(self, serial_objs_dict=None):
        """
        A JSON serializable dict representation of an object.
        """
        d = {"@module": self.__class__.__module__,
             "@class": self.__class__.__name__}

        try:
            parent_module = \
                self.__class__.__module__.split(".", maxsplit=1)[0]
            module_version = import_module(
                parent_module).__version__  # type: ignore
            d["@version"] = str(module_version)
        except (AttributeError, ImportError):
            d["@version"] = None  # type: ignore

        serial_objs_dict = {}

        def recursive_as_dict(obj):
            if isinstance(obj, (list, tuple)):
                return [recursive_as_dict(it) for it in obj]
            if isinstance(obj, dict):
                return {kk: recursive_as_dict(vv) for kk, vv in obj.items()}
            if callable(obj) and not isinstance(obj, GSONable):
                return _serialize_callable(obj, serial_objs_dict=serial_objs_dict)
            if hasattr(obj, "as_dict"):
                name = getattr(obj, "name", str(id(obj)))
                if name not in serial_objs_dict:  # Add the path
                    serial_obj = obj.as_dict(
                        serial_objs_dict=serial_objs_dict)  # serial_objs is modified in place
                    serial_objs_dict[name] = serial_obj
                return {"$type": "ref", "value": name}
            return obj

        d["graph"] = recursive_as_dict(self.simsopt_objs)
        d["simsopt_objs"] = serial_objs_dict
        return d

    @classmethod
    def from_dict(cls, d, serial_objs_dict=None, recon_objs=None):
        graph_subdict = d["graph"]
        serial_objs_dict = d["simsopt_objs"]
        gson_decoder = GSONDecoder()
        recon_objs = {}
        return gson_decoder.process_decoded(
            graph_subdict, serial_objs_dict, recon_objs)


class GSONEncoder(json.JSONEncoder):
    """
    A Json Encoder which supports the GSONable API, plus adds support for
    numpy arrays, datetime objects, bson ObjectIds (requires bson).
    Usage::
        # Add it as a *cls* keyword when using json.dump
        json.dumps(object, cls=GSONEncoder)
    """

    def default(self, o) -> dict:  # pylint: disable=E0202
        """
        Overriding default method for JSON encoding. This method does two
        things: (a) If an object has a to_dict property, return the to_dict
        output. (b) If the @module and @class keys are not in the to_dict,
        add them to the output automatically. If the object has no to_dict
        property, the default Python json encoder default method is called.
        Args:
            o: Python object.
        Return:
            Python dict representation.
        """
        if isinstance(o, datetime.datetime):
            return {"@module": "datetime", "@class": "datetime",
                    "string": str(o)}
        if isinstance(o, UUID):
            return {"@module": "uuid", "@class": "UUID", "string": str(o)}

        if jax is not None and isinstance(o, jax.Array):
            o = np.asarray(o)

        if isinstance(o, np.ndarray):
            if str(o.dtype).startswith("complex"):
                return {
                    "@module": "numpy",
                    "@class": "array",
                    "dtype": str(o.dtype),
                    "data": [o.real.tolist(), o.imag.tolist()],
                }
            return {
                "@module": "numpy",
                "@class": "array",
                "dtype": str(o.dtype),
                "data": o.tolist(),
            }
        if isinstance(o, np.generic):
            return o.item()

        if pd is not None:
            if isinstance(o, pd.DataFrame):
                return {
                    "@module": "pandas",
                    "@class": "DataFrame",
                    "data": o.to_json(
                        default_handler=GSONEncoder().encode),
                }
            if isinstance(o, pd.Series):
                return {
                    "@module": "pandas",
                    "@class": "Series",
                    "data": o.to_json(
                        default_handler=GSONEncoder().encode),
                }

        if bson is not None:
            if isinstance(o, bson.objectid.ObjectId):
                return {"@module": "bson.objectid", "@class": "ObjectId",
                        "oid": str(o)}

        if callable(o) and not isinstance(o, GSONable):
            return _serialize_callable(o)

        try:
            d = o.as_dict()
            if hasattr(o, "name") and "@name" not in d:
                d["@name"] = o.name

            if "@module" not in d:
                d["@module"] = str(o.__class__.__module__)
            if "@class" not in d:
                d["@class"] = str(o.__class__.__name__)
            if "@version" not in d:
                try:
                    parent_module = o.__class__.__module__.split(".")[0]
                    module_version = import_module(
                        parent_module).__version__  # type: ignore
                    d["@version"] = str(module_version)
                except (AttributeError, ImportError):
                    d["@version"] = None
            return d
        except AttributeError:
            return json.JSONEncoder.default(self, o)


class GSONDecoder(json.JSONDecoder):
    """
    A Json Decoder which supports the GSONable API. By default, the
    decoder attempts to find a module and name associated with a dict. If
    found, the decoder will generate a SIMSOPT object as a priority.  If that fails,
    the original decoded dictionary from the string is returned. Note that
    nested lists and dicts containing pymatgen object will be decoded correctly
    as well.
    Usage:
        # Add it as a *cls* keyword when using json.load
        json.loads(json_string, cls=GSONDecoder)
    """

    def process_decoded(self, d, serial_objs_dict=None, recon_objs=None):
        """
        Recursive method to support decoding dicts and lists containing
        GSONable objects.
        """
        if isinstance(d, dict):
            if "$type" in d.keys():
                if d["$type"] == "ref":
                    if d["value"] not in recon_objs:
                        sub_dict = serial_objs_dict[d["value"]]
                        recon_obj = self.process_decoded(sub_dict,
                                                         serial_objs_dict, recon_objs)
                        recon_objs[d["value"]] = recon_obj
                    return recon_objs[d["value"]]
            if "@module" in d and "@class" in d:
                modname = d["@module"]
                classname = d["@class"]
                if classname in GSONable.REDIRECT.get(modname, {}):
                    modname = GSONable.REDIRECT[modname][classname][
                        "@module"]
                    classname = GSONable.REDIRECT[modname][classname][
                        "@class"]
            elif "@module" in d and "@callable" in d:
                modname = d["@module"]
                objname = d["@callable"]
                classname = None
                if d.get("@bound", None) is not None:
                    # if the function is bound to an instance or class, first
                    # deserialize the bound object and then remove the object name
                    # from the function name.
                    obj = self.process_decoded(d["@bound"], serial_objs_dict=serial_objs_dict,
                                               recon_objs=recon_objs)
                    objname = objname.split(".")[1:]
                else:
                    # if the function is not bound to an object, import the
                    # function from the module name
                    obj = __import__(modname, globals(), locals(),
                                     [objname], 0)
                    objname = objname.split(".")
                try:
                    # the function could be nested. e.g., MyClass.NestedClass.function
                    # so iteratively access the nesting
                    for attr in objname:
                        obj = getattr(obj, attr)

                    return obj

                except AttributeError:
                    pass
            else:
                modname = None
                classname = None

            if classname:

                if modname and modname not in ["bson.objectid", "numpy",
                                               "pandas"]:
                    if modname == "datetime" and classname == "datetime":
                        try:
                            dt = datetime.datetime.strptime(d["string"],
                                                            "%Y-%m-%d %H:%M:%S.%f")
                        except ValueError:
                            dt = datetime.datetime.strptime(d["string"],
                                                            "%Y-%m-%d %H:%M:%S")
                        return dt

                    if modname == "uuid" and classname == "UUID":
                        return UUID(d["string"])

                    mod = __import__(modname, globals(), locals(),
                                     [classname], 0)
                    if hasattr(mod, classname):
                        cls_ = getattr(mod, classname)
                        data = {k: v for k, v in d.items() if
                                not k.startswith("@")}
                        if hasattr(cls_, "from_dict"):
                            obj = cls_.from_dict(data, serial_objs_dict, recon_objs)
                            if "@name" in d:
                                recon_objs[d["@name"]] = obj
                            return obj
                        if _is_jax_core_spec_dataclass(cls_):
                            obj = _decode_jax_core_spec_dataclass(
                                cls_,
                                data,
                                self,
                                serial_objs_dict,
                                recon_objs,
                            )
                            if "@name" in d:
                                recon_objs[d["@name"]] = obj
                            return obj
                elif np is not None and modname == "numpy" and classname == "array":
                    if d["dtype"].startswith("complex"):
                        return np.array(
                            [np.array(r) + np.array(i) * 1j for r, i in
                             zip(*d["data"])],
                            dtype=d["dtype"],
                        )
                    return np.array(d["data"], dtype=d["dtype"])
                elif pd is not None and modname == "pandas":
                    if classname == "DataFrame":
                        decoded_data = GSONDecoder().decode(d["data"])
                        return pd.DataFrame(decoded_data)
                    if classname == "Series":
                        decoded_data = GSONDecoder().decode(d["data"])
                        return pd.Series(decoded_data)
                elif (
                        bson is not None) and modname == "bson.objectid" and classname == "ObjectId":
                    return bson.objectid.ObjectId(d["oid"])

            return {self.process_decoded(k, serial_objs_dict, recon_objs): self.process_decoded(v, serial_objs_dict, recon_objs) for
                    k, v in d.items()}

        if isinstance(d, list):
            return [self.process_decoded(x, serial_objs_dict, recon_objs) for x in d]

        return d

    def decode(self, s):
        """
        Overrides decode from JSONDecoder.
        :param s: string
        :return: Object.
        """
        if orjson is not None:
            try:
                d = orjson.loads(s)  # pylint: disable=E1101
            except orjson.JSONDecodeError:  # pylint: disable=E1101
                d = json.loads(s)
        else:
            d = json.loads(s)
        return self.process_decoded(d)


def _is_jax_core_spec_dataclass(cls_) -> bool:
    return cls_.__module__ == _SPEC_MODULE and is_dataclass(cls_)


def _coerce_decoded_spec_field(classname: str, key: str, value: object) -> object:
    if classname == "CoilGroupSpec" and key == "coil_indices":
        return tuple(int(index) for index in value)
    if classname in {"GroupedCoilSetSpec", "CoilSetDofExtractionSpec"} and key in {
        "groups",
        "coils",
    }:
        return tuple(value)
    if classname == "OptimizableDofMapSpec" and key == "owner_segments":
        return tuple(tuple(int(item) for item in segment) for segment in value)
    if classname == "SingleStageSeedSpec" and key == "target_labels":
        return tuple(str(label) for label in value)
    if classname == "SingleStageSeedSpec" and key == "hardware_constants":
        return tuple((str(label), float(val)) for label, val in value)
    return value


def _decode_jax_core_spec_dataclass(
    cls_,
    data: dict,
    decoder: GSONDecoder,
    serial_objs_dict: dict | None,
    recon_objs: dict | None,
):
    decoded = {}
    for field in fields(cls_):
        value = decoder.process_decoded(
            data[field.name],
            serial_objs_dict=serial_objs_dict,
            recon_objs=recon_objs,
        )
        decoded[field.name] = _coerce_decoded_spec_field(
            cls_.__name__,
            field.name,
            value,
        )
    return cls_(**decoded)


def _json_array_dict(value: object) -> dict:
    arr = np.asarray(value)
    if arr.dtype.kind == "c":
        data = [arr.real.tolist(), arr.imag.tolist()]
    else:
        data = arr.tolist()
    return {
        "@module": "numpy",
        "@class": "array",
        "dtype": str(arr.dtype),
        "data": data,
    }


def _is_array_like_for_spec_json(value: object) -> bool:
    if isinstance(value, np.ndarray):
        return True
    return jax is not None and isinstance(value, jax.Array)


def _spec_to_json_value(value: object) -> object:
    if is_dataclass(value):
        return {
            "@module": value.__class__.__module__,
            "@class": value.__class__.__name__,
            **{
                field.name: _spec_to_json_value(getattr(value, field.name))
                for field in fields(value)
            },
        }
    if _is_array_like_for_spec_json(value):
        return _json_array_dict(value)
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, tuple):
        return [_spec_to_json_value(item) for item in value]
    if isinstance(value, list):
        return [_spec_to_json_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _spec_to_json_value(val) for key, val in value.items()}
    return value


def _spec_simson_dict(graph_name: str, spec: object) -> dict:
    return {
        "@module": _SIMSON_MODULE,
        "@class": _SIMSON_CLASS,
        "@version": None,
        "graph": {"$type": "ref", "value": graph_name},
        "simsopt_objs": {
            graph_name: _spec_to_json_value(spec),
        },
    }


def _write_spec_simson(path: str | pathlib.Path, graph_name: str, spec: object) -> None:
    with open(path, "w") as fp:
        json.dump(_spec_simson_dict(graph_name, spec), fp, indent=2)


def save_biot_savart_spec(path: str | pathlib.Path, coil_set_spec: object) -> None:
    """Write a SIMSON-wrapped immutable grouped-coil spec JSON payload."""
    _write_spec_simson(path, "GroupedCoilSetSpec1", coil_set_spec)


def save_surface_rz_fourier_spec(path: str | pathlib.Path, surface_spec: object) -> None:
    """Write a SIMSON-wrapped immutable ``SurfaceRZFourierSpec`` JSON payload."""
    _write_spec_simson(path, "SurfaceRZFourierSpec1", surface_spec)


def save_surface_xyz_fourier_spec(path: str | pathlib.Path, surface_spec: object) -> None:
    """Write a SIMSON-wrapped immutable ``SurfaceXYZFourierSpec`` JSON payload."""
    _write_spec_simson(path, "SurfaceXYZFourierSpec1", surface_spec)


def save_surface_xyz_tensor_fourier_spec(
    path: str | pathlib.Path,
    surface_spec: object,
) -> None:
    """Write a SIMSON-wrapped immutable ``SurfaceXYZTensorFourierSpec`` JSON payload."""
    _write_spec_simson(path, "SurfaceXYZTensorFourierSpec1", surface_spec)


def _rotated_curve_matrix(phi: float, flip: bool) -> np.ndarray:
    rotmat = np.asarray(
        [[cos(phi), -sin(phi), 0.0], [sin(phi), cos(phi), 0.0], [0.0, 0.0, 1.0]],
        dtype=np.float64,
    ).T
    if flip:
        rotmat = rotmat @ np.asarray(
            [[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0, -1.0]],
            dtype=np.float64,
        )
    return rotmat


class _SpecGraphReader:
    def __init__(self, data: dict):
        if data["@module"] != _SIMSON_MODULE or data["@class"] != _SIMSON_CLASS:
            raise ValueError("expected GSON SIMSON wrapper")
        self._data = data
        self._objects = data["simsopt_objs"]
        self._cache: dict[str, object] = {}

    def build(self) -> dict[str, object]:
        graph = self._decode_value(self._data["graph"])
        result: dict[str, object] = {"graph": graph}
        self._add_graph_aliases(result, graph)
        result["objects"] = {
            key: value
            for key, value in self._cache.items()
            if not isinstance(value, (_CurvePayload, _CurrentPayload))
        }
        return result

    def _add_graph_aliases(self, result: dict[str, object], graph: object) -> None:
        from ..jax_core.specs import (
            GroupedCoilSetSpec,
            SurfaceRZFourierSpec,
            SurfaceXYZFourierSpec,
            SurfaceXYZTensorFourierSpec,
        )

        if isinstance(graph, GroupedCoilSetSpec):
            result["coil_set_spec"] = graph
        if isinstance(
            graph,
            (
                SurfaceRZFourierSpec,
                SurfaceXYZFourierSpec,
                SurfaceXYZTensorFourierSpec,
            ),
        ):
            result["surface_spec"] = graph

    def _decode_value(self, value: object) -> object:
        if isinstance(value, dict):
            if "$type" in value:
                if value["$type"] == "ref":
                    return self._resolve_ref(str(value["value"]))
                raise NotImplementedError(
                    f"Unsupported GSON value type: {value['$type']}"
                )
            if "@module" in value:
                module = value["@module"]
                classname = value["@class"]
                if module == "numpy" and classname == "array":
                    return GSONDecoder().process_decoded(value, {}, {})
                if module == _SPEC_MODULE:
                    return self._read_spec_node(value)
                raise NotImplementedError(
                    f"{module}.{classname}"
                )
            if "@class" in value:
                raise NotImplementedError(f"{value['@class']}")
            return {key: self._decode_value(val) for key, val in value.items()}
        if isinstance(value, list):
            return [self._decode_value(item) for item in value]
        return value

    def _resolve_ref(self, name: str) -> object:
        if name not in self._cache:
            self._cache[name] = self._read_object(self._objects[name])
        return self._cache[name]

    def _read_object(self, node: dict) -> object:
        module = node["@module"]
        classname = node["@class"]
        if module == _SPEC_MODULE:
            return self._read_spec_node(node)
        readers = {
            ("simsopt._core.optimizable", "DOFs"): self._read_dofs,
            ("simsopt.field.coil", "Current"): self._read_current,
            ("simsopt.field.coil", "ScaledCurrent"): self._read_scaled_current,
            ("simsopt.geo.curvexyzfourier", "CurveXYZFourier"): (
                self._read_curve_xyz_fourier
            ),
            ("simsopt.geo.curvecwsfourier", "CurveCWSFourierCPP"): (
                self._read_curve_cws_fourier_rz
            ),
            ("simsopt.geo.curve", "RotatedCurve"): self._read_rotated_curve,
            ("simsopt.geo.surfacerzfourier", "SurfaceRZFourier"): (
                self._read_surface_rz_fourier
            ),
            ("simsopt.geo.surfacexyzfourier", "SurfaceXYZFourier"): (
                self._read_surface_xyz_fourier
            ),
            ("simsopt.geo.surfacexyztensorfourier", "SurfaceXYZTensorFourier"): (
                self._read_surface_xyz_tensor_fourier
            ),
            ("simsopt.field.coil", "Coil"): self._read_coil,
            ("simsopt.field.biotsavart", "BiotSavart"): self._read_biot_savart,
        }
        key = (module, classname)
        if key not in readers:
            raise NotImplementedError(f"{module}.{classname}")
        return readers[key](node)

    def _read_dofs(self, node: dict) -> np.ndarray:
        return np.asarray(self._decode_value(node["x"]), dtype=np.float64)

    def _read_current(self, node: dict) -> _CurrentPayload:
        from ..jax_core import make_current_value_spec

        dofs = self._decode_value(node["dofs"])
        value = np.asarray(dofs, dtype=np.float64)[0]
        return _CurrentPayload(make_current_value_spec(value), 1.0)

    def _read_scaled_current(self, node: dict) -> _CurrentPayload:
        base = self._decode_value(node["current_to_scale"])
        return _CurrentPayload(base.current, base.scale * float(node["scale"]))

    def _read_curve_xyz_fourier(self, node: dict) -> object:
        from ..jax_core import make_curve_xyzfourier_spec

        return make_curve_xyzfourier_spec(
            dofs=self._decode_value(node["dofs"]),
            quadpoints=self._decode_value(node["quadpoints"]),
            order=int(node["order"]),
        )

    def _read_curve_cws_fourier_rz(self, node: dict) -> object:
        from ..jax_core import make_curve_cwsfourier_rz_spec

        surface = self._decode_value(node["surf"])
        return make_curve_cwsfourier_rz_spec(
            dofs=self._decode_value(node["dofs"]),
            quadpoints=self._decode_value(node["quadpoints"]),
            surface=surface,
            order=int(node["order"]),
            G=float(node["G"]),
            H=float(node["H"]),
        )

    def _read_rotated_curve(self, node: dict) -> _CurvePayload:
        base = self._decode_value(node["curve"])
        rotmat = _rotated_curve_matrix(float(node["phi"]), bool(node["flip"]))
        if isinstance(base, _CurvePayload):
            rotmat = np.asarray(base.rotmat, dtype=np.float64) @ rotmat
            return _CurvePayload(base.curve, rotmat)
        return _CurvePayload(base, rotmat)

    def _read_surface_rz_fourier(self, node: dict) -> object:
        from ..jax_core.surface_rzfourier import surface_rz_fourier_spec_from_dofs

        return surface_rz_fourier_spec_from_dofs(
            self._decode_value(node["dofs"]),
            quadpoints_phi=self._decode_value(node["quadpoints_phi"]),
            quadpoints_theta=self._decode_value(node["quadpoints_theta"]),
            mpol=int(node["mpol"]),
            ntor=int(node["ntor"]),
            nfp=int(node["nfp"]),
            stellsym=bool(node["stellsym"]),
        )

    def _read_surface_xyz_fourier(self, node: dict) -> object:
        from ..jax_core import make_surface_xyz_fourier_spec

        return make_surface_xyz_fourier_spec(
            dofs=self._decode_value(node["dofs"]),
            quadpoints_phi=self._decode_value(node["quadpoints_phi"]),
            quadpoints_theta=self._decode_value(node["quadpoints_theta"]),
            mpol=int(node["mpol"]),
            ntor=int(node["ntor"]),
            nfp=int(node["nfp"]),
            stellsym=bool(node["stellsym"]),
        )

    def _read_surface_xyz_tensor_fourier(self, node: dict) -> object:
        from ..jax_core import make_surface_xyz_tensor_fourier_spec

        return make_surface_xyz_tensor_fourier_spec(
            dofs=self._decode_value(node["dofs"]),
            quadpoints_phi=self._decode_value(node["quadpoints_phi"]),
            quadpoints_theta=self._decode_value(node["quadpoints_theta"]),
            mpol=int(node["mpol"]),
            ntor=int(node["ntor"]),
            nfp=int(node["nfp"]),
            stellsym=bool(node["stellsym"]),
        )

    def _read_coil(self, node: dict) -> object:
        from ..jax_core import make_coil_spec

        curve = self._decode_value(node["curve"])
        current = self._decode_value(node["current"])
        rotmat = None
        curve_spec = curve
        if isinstance(curve, _CurvePayload):
            curve_spec = curve.curve
            rotmat = curve.rotmat
        return make_coil_spec(
            curve=curve_spec,
            current=current.current,
            rotmat=rotmat,
            scale=current.scale,
        )

    def _read_biot_savart(self, node: dict) -> object:
        from ..jax_core.field import grouped_coil_set_spec_from_coil_specs

        return grouped_coil_set_spec_from_coil_specs(
            tuple(self._decode_value(coil_ref) for coil_ref in node["coils"])
        )

    def _read_spec_node(self, node: dict) -> object:
        from ..jax_core import (
            make_coil_group_spec,
            make_grouped_coil_set_spec,
            make_surface_rzfourier_spec,
            make_surface_xyz_fourier_spec,
            make_surface_xyz_tensor_fourier_spec,
        )

        classname = str(node["@class"])
        data = {
            key: self._decode_value(value)
            for key, value in node.items()
            if not key.startswith("@")
        }
        if classname == "CoilGroupSpec":
            return make_coil_group_spec(
                data["gammas"],
                data["gammadashs"],
                data["currents"],
                data["coil_indices"],
            )
        if classname == "GroupedCoilSetSpec":
            return make_grouped_coil_set_spec(tuple(data["groups"]))
        if classname == "SurfaceRZFourierSpec":
            return make_surface_rzfourier_spec(
                rc=data["rc"],
                zs=data["zs"],
                rs=data["rs"],
                zc=data["zc"],
                quadpoints_phi=data["quadpoints_phi"],
                quadpoints_theta=data["quadpoints_theta"],
                nfp=int(data["nfp"]),
                stellsym=bool(data["stellsym"]),
            )
        if classname == "SurfaceXYZFourierSpec":
            return make_surface_xyz_fourier_spec(
                dofs=data["dofs"],
                quadpoints_phi=data["quadpoints_phi"],
                quadpoints_theta=data["quadpoints_theta"],
                nfp=int(data["nfp"]),
                stellsym=bool(data["stellsym"]),
                mpol=int(data["mpol"]),
                ntor=int(data["ntor"]),
            )
        if classname == "SurfaceXYZTensorFourierSpec":
            return make_surface_xyz_tensor_fourier_spec(
                dofs=data["dofs"],
                quadpoints_phi=data["quadpoints_phi"],
                quadpoints_theta=data["quadpoints_theta"],
                nfp=int(data["nfp"]),
                stellsym=bool(data["stellsym"]),
                mpol=int(data["mpol"]),
                ntor=int(data["ntor"]),
            )
        raise NotImplementedError(f"{_SPEC_MODULE}.{classname}")


def load_specs(path: str | pathlib.Path) -> dict[str, object]:
    """Load immutable JAX specs directly from a SIMSON JSON graph."""
    with open(path) as fp:
        data = json.load(fp)
    return _SpecGraphReader(data).build()


class GSONError(Exception):
    """
    Exception class for serialization errors.
    """


def jsanitize(obj, strict=False, allow_bson=False, enum_values=False,
              recursive_gsonable=False, serial_objs_dict=None):
    """
    This method cleans an input json-like object, either a list or a dict or
    some sequence, nested or otherwise, by converting all non-string
    dictionary keys (such as int and float) to strings, and also recursively
    encodes all objects using GSON's as_dict() protocol.
    Args:
        obj: input json-like object.
        strict (bool): This parameters sets the behavior when jsanitize
            encounters an object it does not understand. If strict is True,
            jsanitize will try to get the as_dict() attribute of the object. If
            no such attribute is found, an attribute error will be thrown. If
            strict is False, jsanitize will simply call str(object) to convert
            the object to a string representation.
        allow_bson (bool): This parameters sets the behavior when jsanitize
            encounters a bson supported type such as objectid and datetime. If
            True, such bson types will be ignored, allowing for proper
            insertion into MongoDB databases.
        enum_values (bool): Convert Enums to their values.
        recursive_gsonable (bool): If True, uses .as_dict() for GSONables regardless
            of the value of strict.
        serial_objs_dict: Dictionary of serialized objects produced during jsonification
    Returns:
        Sanitized dict that can be json serialized.
    """
    if serial_objs_dict is None:
        serial_objs_dict = {}
    if isinstance(obj, Enum) and enum_values:
        return obj.value

    if allow_bson and (
            isinstance(obj, (datetime.datetime, bytes)) or (
            bson is not None and isinstance(obj, bson.objectid.ObjectId))
    ):
        return obj
    if isinstance(obj, (list, tuple)):
        return [jsanitize(i, strict=strict, allow_bson=allow_bson,
                          enum_values=enum_values) for i in obj]
    if np is not None and isinstance(obj, np.ndarray):
        return [jsanitize(i, strict=strict, allow_bson=allow_bson,
                          enum_values=enum_values) for i in obj.tolist()]
    if np is not None and isinstance(obj, np.generic):
        return obj.item()
    if pd is not None and isinstance(obj, (pd.Series, pd.DataFrame)):
        return obj.to_dict()
    if isinstance(obj, dict):
        return {
            str(k): jsanitize(
                v,
                strict=strict,
                allow_bson=allow_bson,
                enum_values=enum_values,
                recursive_gsonable=recursive_gsonable,
            )
            for k, v in obj.items()
        }
    if isinstance(obj, (int, float)):
        return obj
    if obj is None:
        return None
    if isinstance(obj, pathlib.Path):
        return str(obj)

    if callable(obj) and not isinstance(obj, GSONable):
        try:
            return _serialize_callable(obj)
        except TypeError:
            pass

    if recursive_gsonable and isinstance(obj, GSONable):
        return obj.as_dict(serial_objs_dict=serial_objs_dict)

    if not strict:
        return str(obj)

    if isinstance(obj, str):
        return obj

    return jsanitize(
        obj.as_dict(serial_objs_dict=serial_objs_dict),
        strict=strict,
        allow_bson=allow_bson,
        enum_values=enum_values,
        recursive_gsonable=recursive_gsonable,
    )


def _serialize_callable(o, serial_objs_dict={}):
    if isinstance(o, types.BuiltinFunctionType):
        # don't care about what builtin functions (sum, open, etc) are bound to
        bound = None
    else:
        # bound methods (i.e., instance methods) have a __self__ attribute
        # that points to the class/module/instance
        bound = getattr(o, "__self__", None)

    # we are only able to serialize bound methods if the object the method is
    # bound to is itself serializable
    if bound is not None:
        if isinstance(bound, GSONable):
            bound = bound.as_dict(serial_objs_dict=serial_objs_dict)
        else:
            try:
                bound = GSONEncoder().default(bound)
            except TypeError:
                raise TypeError(
                    "Only bound methods of classes or GSONable instances are supported.")

    return {
        "@module": o.__module__,
        "@callable": getattr(o, "__qualname__", o.__name__),
        "@bound": bound,
    }
