"""Generate the tracked official-reference fixture from a campaign capture tree.

Every input root is a command-line argument: the capture tree, the contract directory and the official clone all
live outside the repository (or under a git-ignored directory), so nothing here may hard-code them.  The generator
refuses to write unless each case's official script hashes to the value its contract recorded, which is what ties a
fixture number to upstream commit ``9e027eac38028d57aa23777be52a781aa860e347``.

Regenerate the shipped set with::

    PYTHONDONTWRITEBYTECODE=1 bash .artifacts/official-scope-cleanup-20260919/run-python.sh \\
        examples/jax/parity/official_reference/build_official_reference.py \\
        --campaign-root .artifacts/official-mirror-closure-20260919 \\
        --manifest examples/jax/manifest.json \\
        --official-src /data/code/columbia/simsopt-official-reference-9e027eac3/src \\
        --upstream-commit 9e027eac38028d57aa23777be52a781aa860e347 \\
        --output examples/jax/parity/official_reference/9e027eac3
"""

from __future__ import annotations

import argparse
import hashlib
import json
from collections.abc import Mapping, Sequence
from pathlib import Path

import numpy as np

from examples.jax.parity.official_reference import (
    CANONICAL_VARIANT,
    SENSITIVITY_ROOT,
    INLINE_ELEMENT_LIMIT,
    SCHEMA_VERSION,
    ArrayDigest,
    encode_nonfinite,
)

#: Directory name pattern of a canonical capture under the reference-simple packet.
SIMPLE_CAPTURE_GLOB = "captured-*-omp1"

#: Directory name of a canonical capture under the claude packet.
CLAUDE_CAPTURE_NAME = "captured-omp1"

#: Extra captured runs of the same official script, as ``variant name -> capture directory name``.
VARIANT_DIRECTORY_NAMES = {"ci": "captured-omp1-ci"}

#: Sub-directory of the output holding the sensitivity records.
SENSITIVITY_DIRECTORY_NAME = SENSITIVITY_ROOT.name

#: Per-run artefacts of the band-sampling investigation.
SENSITIVITY_SUMMARY_NAME = "band-sampling.json"
SENSITIVITY_PERTURBATION_NAME = "perturbation.json"
SENSITIVITY_RUN_NAME = "run.json"

#: The protocol was pre-registered before any sample existed; this text is copied into every record.
SENSITIVITY_PROTOCOL_TEXT = (
    "Nine runs of the UNMODIFIED official script on the official build "
    "(/data/code/columbia/simsopt-official-reference-9e027eac3/venv), one thread, the capture lane's environment. "
    "k = 0 is the unperturbed rerun and reproduces the canonical capture bitwise. For k = 1..8 only the FIRST "
    "provider call's start vector is moved by exactly one unit in the last place per entry; everything else is "
    "verbatim. These are upstream's own numbers: the record carries no band, ceiling or other derived bound."
)
SENSITIVITY_PERTURBATION_RULE = "x0' = np.nextafter(x0, s * np.inf)"
SENSITIVITY_SEED_RULE = (
    "s = np.random.RandomState(20260920 + k).choice([-1.0, 1.0], size=x0.size)"
)
SENSITIVITY_PERTURBED_CALL_INDEX = 0
SENSITIVITY_UNPERTURBED_K = 0
SENSITIVITY_PRE_REGISTRATION = ".artifacts/official-mirror-closure-20260919/d1-diagnostic/NOTES.md (rule v2, fixed 2026-09-20 02:52 EDT)"

#: Capture payload file names.
CAPTURE_JSON_NAME = "capture.json"
CAPTURE_ARRAYS_NAME = "capture-arrays.npz"

README_INTRO = """\
# Official reference fixture — upstream simsopt `{commit}`

Generated by `examples/jax/parity/official_reference/build_official_reference.py`; read by
`examples.jax.parity.official_reference.load_official_reference`. This is the ONE tracked home for numbers measured
on the official simsopt build, so a test can compare a JAX lane against upstream on a clean checkout instead of
reading the git-ignored campaign capture tree or a pasted literal.

One `<case_id>.json` per official case. A case is official iff an upstream source file in the `source_catalog` of
`examples/jax/manifest.json` names it as its `mirror_example_id` with `port_status` `ready`.

Each file is compact JSON (sorted keys, `repr`-exact floats, one trailing newline) holding: the upstream commit, the
official script path and its sha256, the capture provenance (campaign-relative directory, sha256 of `capture.json`
and of `capture-arrays.npz`, thread environment, interpreter/library versions the capture recorded), every provider
call the official run made, and every observable.

Value rule, the same for every case:

* a **scalar** (`float`, `int`, `bool`, `str`, `null`) is stored inline;
* an **array** always carries `shape`, `dtype`, `count`, `sha256` of its C-contiguous little-endian float64 bytes,
  `min`, `max`, `sum`, `l2`, and additionally carries flat C-order `values` when `count <= {limit}`
  (`INLINE_ELEMENT_LIMIT`). A larger array is a digest only and `array()` refuses it;
* anything else is a **structure**, stored verbatim.

The top-level `capture`, `provider_calls` and `observables` are always the **canonical** record: the official run at
the script's own shipped scale. A case that upstream also ran under a reduced configuration carries that run under
the optional top-level `variants` key, in exactly the same shape, and the loader reaches it with
`load_official_reference(case_id, variant="ci")`; `official_variants(case_id)` lists what a case has.

The `ci` variant is upstream's own `in_github_actions` configuration of the SAME official script at `{commit}`,
captured with the `CI` environment variable set, so the script takes its reduced-resolution branch (for
`permanent_magnet_MUSE.py`: `K=100, nBacktracking=50, max_nMagnets=20, downsample=100, nphi=ntheta=2,
nHistory=20`). It is the official counterpart of a BOUNDED lane and is evidence for bounded checks only: it is
never a substitute for the canonical shipped-scale record, and the two must not be mixed in one comparison.

JSON cannot spell a non-finite float, so every non-finite value — scalar, array element, digest statistic, or a leaf
inside a structure or an optimizer option — is written as `{{"$nonfinite": "inf" | "-inf" | "nan"}}` and decoded back
by the loader.

## `sensitivity/`

`sensitivity/<case_id>.json` records UPSTREAM's OWN end-point scatter for a case whose optimizer is chaotic at the
rounding level. Nine runs of the unmodified official script on the official build, one thread: `k = 0` unperturbed
(it reproduces the canonical capture bitwise, which the tests check) and `k = 1..8` with ONLY the first provider
call's start vector moved by one unit in the last place per entry, `x0' = np.nextafter(x0, s * np.inf)` with
`s = np.random.RandomState(20260920 + k).choice([-1.0, 1.0], size=x0.size)`. The protocol was pre-registered in
`.artifacts/official-mirror-closure-20260919/d1-diagnostic/NOTES.md` (rule v2) before any sample existed.

Each record carries the observable name (upstream's capture key), the `lane_observable` (the port lane's key of the same
quantity, which the quality band judges; identical to `observable` unless the capture names it differently, as coil forces'
`stage2:final:objective` / `final:objective`), the protocol, and per `k`: the end value at full precision, every provider
call's `status`, `success`, `nit`, `nfev`, `njev`, `message` and `fun`, and the sha256 of that run's `capture.json`
and of its perturbation record. Read it with `load_official_sensitivity(case_id)` and
`official_sensitivity_case_ids()`.

These are upstream's numbers and nothing else: **the fixture computes no band, ceiling, spread or tolerance from
them**, and it holds no branch-side value. Whoever needs a bound derives it in their own code from these values and
says so there. Note also that `fun` is what the provider reported, which is not always the end value: for
`native-stage-two-optimization-finitebuild` the official script scales the objective it hands the optimizer by
`1e-4`, so `end_value` (the unscaled `final:objective`) is `1e4` times the reported `fun`.

## `scatter/`

`scatter/<case_id>.<scale>.json` records UPSTREAM's OWN end states at one of the parity harness's scales, for a case
whose end point is path dependent (`native-stage-two-optimization-planar-coils`) or whose end STATE -- which
solution the workflow lands on -- is not determined by its input at all (`native-boozer`, whose first stage stops at
its 300-iteration cap and whose Boozer solves then converge onto one of several surfaces). Runs of the official script
on the official build, one thread, the same one-ulp protocol as `sensitivity/` (`k = 0` unperturbed, `k = 1..8`
with ONLY the first provider call's start vector moved by one unit in the last place per entry, signs from
`np.random.RandomState(20260920 + k)`), pre-registered before any sample was drawn. At `native_default` the runner
body is the official script verbatim and `k = 0` reproduces the canonical capture bitwise; at `bounded` it is the
official body with ONLY its scale lines changed to the harness's bounded configuration, and the record stores that
diff (`runner.body_diff`).

Each record maps the port lane's observable keys to upstream's capture keys (`capture_keys`) and holds, per `k`,
every provider call's outcome, whether every upstream stage the record names succeeded (`workflow_success`), the
sha256 of that run's `capture.json` and perturbation record, and the end-state values under LANE keys, element-exact.
Read it with `load_upstream_scatter(case_id, scale)`; `upstream_scatter_records()` lists what exists; the records are
written by `examples/jax/parity/official_reference/build_upstream_scatter.py`.

As for `sensitivity/`, these are upstream's numbers and nothing else: **the fixture computes no band, set or bound**.
The contracts derived from them live in `examples/jax/parity/official_scatter_contracts.py` and state their
derivation there.

## `tracing/`

`tracing/<case_id>.json` records UPSTREAM's OWN trajectory scatter for the three tracing mirrors, whose observable is
a whole set of trajectories rather than one optimizer end value. It is written by
`examples/jax/parity/official_reference/build_official_tracing_scatter.py` from the tracing-sampling investigation
and read with `load_official_tracing_scatter(case_id)` and `official_tracing_scatter_case_ids()`. Nine runs of the
official script bytes on the official build, one thread: `k = 0` unperturbed and `k = 1..8` with ONLY the start data
of the traced objects moved by one unit in the last place per entry, `start' = np.nextafter(start, s * np.inf)` with
`s = np.random.RandomState(20260920 + k).choice([-1.0, 1.0], size=start.size)` (field lines: the `R0` and `Z0`
arrays of `compute_fieldlines`; particles: the `xyz_inits` of `trace_particles`). The protocol was pre-registered in
`.artifacts/official-mirror-closure-20260919/d1-diagnostic/NOTES.md` before any sample existed.

Each record carries the line count, the protocol, the unperturbed run's terminal-status histogram, its total number
of recorded hits and the sha256 of every canonical observable this fixture holds element-exact, and per `k` the
sha256 of that run's `capture.json` and of its perturbation record, what the perturbation moved, and the scatter
quantities (a)-(e) of the investigation report: status changes, hit-count differences per line and per plane, the
final-time difference, the final-state and final-position distances, and the hit-to-section geometry. A quantity that
only some cases have is recorded only by those cases: (f) the final parallel-speed fraction, which the guiding-centre
case has and a field line has not, so the RECORD is what says which case measured which quantity.
`maxima_over_k` is the element-wise maximum over `k = 1..8`. The `k = 0` run reproduces the canonical capture
bitwise: the generator re-hashes every canonical observable held element-exact and refuses to write on a difference,
and `tests/jax/examples/test_official_tracing_scatter_fixture.py` checks the tracked bytes.

As for `sensitivity/`, these are upstream's numbers and nothing else: **the fixture computes no ceiling, band,
spread or tolerance from them**. The shipped-scale tracing contract derives its ceilings in
`examples/jax/parity/official_tracing_contract.py` and states the derivation there.

`tests/jax/examples/test_official_reference_fixture.py` checks the table below against the files: editing a number
by hand without regenerating the set leaves the two out of step.

| case_id | official_script | official_script_sha256 | canonical capture | variants |
| --- | --- | --- | --- | --- |
"""


def sha256_file(path: Path) -> str:
    """sha256 of the bytes of ``path``."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def official_case_ids_from_manifest(manifest_path: Path) -> tuple[str, ...]:
    """Case ids an upstream source claims as its shipped mirror."""
    catalog = json.loads(manifest_path.read_text(encoding="utf-8"))["source_catalog"]
    return tuple(
        sorted(
            str(entry["mirror_example_id"])
            for entry in catalog
            if entry["mirror_example_id"] is not None
            and entry["port_status"] == "ready"
        )
    )


def resolve_capture_directory(
    case_id: str, claude_runs: Path, simple_runs: Path
) -> Path:
    """The canonical capture directory of ``case_id``, without a per-case table.

    A case captured by the reference-simple packet keeps exactly one ``captured-*-omp1`` directory, which is the
    CONTROLLED replay where one exists and the natural run otherwise; every other case is captured by the claude
    packet under ``captured-omp1`` (the ``-ci`` sibling is a second, non-canonical run).
    """
    simple_case = simple_runs / case_id
    if simple_case.is_dir():
        candidates = sorted(
            path for path in simple_case.glob(SIMPLE_CAPTURE_GLOB) if path.is_dir()
        )
        if len(candidates) != 1:
            raise SystemExit(
                f"{case_id}: expected exactly one {SIMPLE_CAPTURE_GLOB} directory under {simple_case}, "
                f"found {[path.name for path in candidates]}"
            )
        return candidates[0]
    return claude_runs / case_id / CLAUDE_CAPTURE_NAME


def nested_shape(value: object) -> tuple[int, ...] | None:
    """Shape of a rectangular nested list, ``()`` for a non-list, ``None`` when ragged or empty."""
    if not isinstance(value, list):
        return ()
    inner = [nested_shape(item) for item in value]
    if len(inner) == 0 or len(set(inner)) != 1 or inner[0] is None:
        return None
    return (len(inner), *inner[0])


def is_numeric_array(value: object) -> bool:
    """True when ``value`` is a rectangular nested list whose every leaf is a number or a bool."""
    shape = nested_shape(value)
    if shape is None or shape == ():
        return False
    return all(isinstance(leaf, (bool, int, float)) for leaf in _leaves(value))


def _leaves(value: object) -> list[object]:
    if isinstance(value, list):
        return [leaf for item in value for leaf in _leaves(item)]
    return [value]


def array_entry(values: np.ndarray) -> dict[str, object]:
    """Fixture entry for one array: always the digest, plus exact values when small enough."""
    digest = ArrayDigest.of(values)
    entry: dict[str, object] = {"kind": "array", **digest.as_payload()}
    if digest.count <= INLINE_ELEMENT_LIMIT:
        entry["values"] = encode_nonfinite(
            np.ascontiguousarray(values).reshape(-1).tolist()
        )
    return entry


def observable_entry(value: object) -> dict[str, object]:
    """Fixture entry for one JSON observable, by the single value rule."""
    if is_numeric_array(value):
        return array_entry(np.asarray(value))
    if isinstance(value, (bool, int, float, str)) or value is None:
        return {"kind": "scalar", "value": encode_nonfinite(value)}
    return {"kind": "structure", "value": encode_nonfinite(value)}


def provider_call_entry(index: int, call: Mapping[str, object]) -> dict[str, object]:
    """Fixture entry for one optimizer call: its settings and the terminal facts of its result."""
    options = call.get("options")
    if options is None:
        options = call.get("keywords")
    if options is None:
        options = {}
    result = call["result"]
    terminal = {
        name: item
        for name, item in dict(result).items()
        if isinstance(item, (bool, int, float, str)) or item is None
    }
    return {
        "index": index,
        "function": call["function"],
        "method": call.get("method"),
        "options": encode_nonfinite(options),
        "tol": encode_nonfinite(call.get("tol")),
        "result": encode_nonfinite(terminal),
    }


def capture_record(
    case_id: str, capture_directory: Path, campaign_root: Path
) -> dict[str, object]:
    """The provenance, provider calls and observables of ONE captured run of ``case_id``."""
    capture_json = capture_directory / CAPTURE_JSON_NAME
    capture = json.loads(capture_json.read_text(encoding="utf-8"))
    arrays_path = capture_directory / CAPTURE_ARRAYS_NAME
    has_arrays = "array_file" in capture

    observables: dict[str, object] = {
        str(key): observable_entry(value)
        for key, value in capture["observables"].items()
    }
    if has_arrays:
        with np.load(arrays_path) as stored:
            for name in stored.files:
                if name in observables:
                    raise SystemExit(
                        f"{case_id}: {name!r} is both a JSON observable and a stored array"
                    )
                observables[str(name)] = array_entry(stored[name])

    return {
        "capture": {
            "path": capture_directory.resolve()
            .relative_to(campaign_root.resolve())
            .as_posix(),
            "capture_json_sha256": sha256_file(capture_json),
            "array_file_sha256": sha256_file(arrays_path) if has_arrays else None,
            "threads": capture["threads"],
            "python": capture.get("python"),
            "numpy": capture.get("numpy"),
            "scipy": capture.get("scipy"),
        },
        "provider_calls": [
            provider_call_entry(index, call)
            for index, call in enumerate(capture["optimizer_calls"])
        ],
        "observables": observables,
    }


def resolve_variant_directory(
    case_id: str, directory_name: str, claude_runs: Path, simple_runs: Path
) -> Path | None:
    """Directory of a named non-canonical capture of ``case_id``, or ``None`` when that case has none."""
    for runs_root in (claude_runs, simple_runs):
        candidate = runs_root / case_id / directory_name
        if (candidate / CAPTURE_JSON_NAME).is_file():
            return candidate
    return None


def build_case_payload(
    case_id: str,
    capture_directory: Path,
    campaign_root: Path,
    contracts: Path,
    official_src: Path,
    upstream_commit: str,
    variant_directories: Mapping[str, Path],
) -> dict[str, object]:
    """Assemble the fixture payload of one case, verifying the official script hash first.

    The canonical record stays at the top level; every other captured run of the same official script goes under
    the optional ``variants`` key, keyed by variant name, in exactly the same shape.
    """
    contract = json.loads((contracts / f"{case_id}.json").read_text(encoding="utf-8"))
    official_script = str(contract["official_script"])
    recorded_sha = str(contract["script_sha256"])
    measured_sha = sha256_file(official_src / official_script)
    if measured_sha != recorded_sha:
        raise SystemExit(
            f"{case_id}: {official_src / official_script} hashes to {measured_sha}, but the contract records "
            f"{recorded_sha}; the clone is not at {upstream_commit}"
        )

    payload: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "case_id": case_id,
        "upstream_commit": upstream_commit,
        "official_script": official_script,
        "official_script_sha256": recorded_sha,
        **capture_record(case_id, capture_directory, campaign_root),
    }
    if variant_directories:
        payload["variants"] = {
            name: capture_record(case_id, directory, campaign_root)
            for name, directory in sorted(variant_directories.items())
        }
    return payload


def provider_outcome_entry(index: int, call: Mapping[str, object]) -> dict[str, object]:
    """The terminal outcome of one provider call of a sensitivity run."""
    result = dict(call["result"])
    return {
        "index": index,
        "method": call.get("method"),
        "status": result["status"],
        "success": result["success"],
        "nit": result["nit"],
        "nfev": result["nfev"],
        "njev": result["njev"],
        "message": result["message"],
        "fun": encode_nonfinite(result["fun"]),
    }


def build_sensitivity_payload(
    case_id: str,
    observable: str,
    lane_observable: str,
    sampling_root: Path,
    summary_runs: Sequence[Mapping[str, object]],
    official_script: str,
    official_script_sha256: str,
    upstream_commit: str,
) -> dict[str, object]:
    """Assemble one sensitivity record from the per-run artefacts, cross-checked against the sampling summary."""
    runs: list[dict[str, object]] = []
    threads: dict[str, str] = {}
    for summary_run in sorted(summary_runs, key=lambda entry: int(entry["k"])):
        k = int(summary_run["k"])
        directory = sampling_root / "runs" / case_id / f"k{k}"
        run_record = json.loads(
            (directory / SENSITIVITY_RUN_NAME).read_text(encoding="utf-8")
        )
        if run_record["exit_code"] != 0:
            raise SystemExit(
                f"{case_id} k={k}: the official run exited {run_record['exit_code']}; a failed run is not evidence"
            )
        capture_path = directory / CAPTURE_JSON_NAME
        capture = json.loads(capture_path.read_text(encoding="utf-8"))
        end_value = capture["observables"][observable]
        if end_value != summary_run["band_value"]:
            raise SystemExit(
                f"{case_id} k={k}: capture {observable} is {end_value!r} but the sampling summary records "
                f"{summary_run['band_value']!r}"
            )
        threads = {str(name): str(value) for name, value in capture["threads"].items()}
        runs.append(
            {
                "k": k,
                "end_value": encode_nonfinite(end_value),
                "provider_calls": [
                    provider_outcome_entry(index, call)
                    for index, call in enumerate(capture["optimizer_calls"])
                ],
                "capture_sha256": sha256_file(capture_path),
                "perturbation_sha256": sha256_file(
                    directory / SENSITIVITY_PERTURBATION_NAME
                ),
            }
        )
    return {
        "schema_version": SCHEMA_VERSION,
        "case_id": case_id,
        "upstream_commit": upstream_commit,
        "official_script": official_script,
        "official_script_sha256": official_script_sha256,
        "observable": observable,
        "lane_observable": lane_observable,
        "protocol": {
            "text": SENSITIVITY_PROTOCOL_TEXT,
            "perturbation_rule": SENSITIVITY_PERTURBATION_RULE,
            "seed_rule": SENSITIVITY_SEED_RULE,
            "perturbed_call_index": SENSITIVITY_PERTURBED_CALL_INDEX,
            "unperturbed_k": SENSITIVITY_UNPERTURBED_K,
            "pre_registered_in": SENSITIVITY_PRE_REGISTRATION,
            "threads": threads,
        },
        "runs": runs,
    }


def build_sensitivity_payloads(
    sampling_root: Path,
    case_payloads: Mapping[str, Mapping[str, object]],
    upstream_commit: str,
) -> dict[str, dict[str, object]]:
    """One record per case the sampling directory covers; empty when that directory is absent."""
    summary_path = sampling_root / SENSITIVITY_SUMMARY_NAME
    if not summary_path.is_file():
        return {}
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    payloads = {}
    for case_id in sorted(summary):
        if case_id not in case_payloads:
            raise SystemExit(
                f"{case_id}: sampled for sensitivity but it is not an official case"
            )
        case_payload = case_payloads[case_id]
        payloads[case_id] = build_sensitivity_payload(
            case_id=case_id,
            observable=str(summary[case_id]["observable"]),
            lane_observable=str(summary[case_id]["lane_observable"]),
            sampling_root=sampling_root,
            summary_runs=summary[case_id]["runs"],
            official_script=str(case_payload["official_script"]),
            official_script_sha256=str(case_payload["official_script_sha256"]),
            upstream_commit=upstream_commit,
        )
    return payloads


def render_case_file(payload: Mapping[str, object]) -> str:
    """Compact, deterministic JSON text: sorted keys, ``repr``-exact floats, one trailing newline."""
    return (
        json.dumps(
            payload,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
            ensure_ascii=True,
        )
        + "\n"
    )


def render_readme(
    payloads: Sequence[Mapping[str, object]], upstream_commit: str
) -> str:
    """The tracked provenance table plus what the file set is."""
    rows = "".join(
        "| `{case_id}` | `{script}` | `{sha}` | `{capture}` | {variants} |\n".format(
            case_id=payload["case_id"],
            script=payload["official_script"],
            sha=payload["official_script_sha256"],
            capture=dict(payload["capture"])["path"],
            variants=" ".join(
                f"`{name}`" for name in sorted(dict(payload.get("variants", {})))
            )
            or "--",
        )
        for payload in payloads
    )
    return (
        README_INTRO.format(commit=upstream_commit, limit=INLINE_ELEMENT_LIMIT) + rows
    )


def write_official_reference(
    *,
    campaign_root: Path,
    manifest: Path,
    contracts: Path,
    official_src: Path,
    upstream_commit: str,
    output: Path,
    band_sampling: Path,
    variants: Mapping[str, str] = VARIANT_DIRECTORY_NAMES,
) -> tuple[Path, ...]:
    """Write one JSON file per official case plus the README table; return the paths written, sorted."""
    claude_runs = campaign_root / "claude" / "runs"
    simple_runs = campaign_root / "reference-simple" / "runs"
    payloads = []
    for case_id in official_case_ids_from_manifest(manifest):
        found = {
            name: directory
            for name, directory_name in variants.items()
            for directory in [
                resolve_variant_directory(
                    case_id, directory_name, claude_runs, simple_runs
                )
            ]
            if directory is not None
        }
        payloads.append(
            build_case_payload(
                case_id=case_id,
                capture_directory=resolve_capture_directory(
                    case_id, claude_runs, simple_runs
                ),
                campaign_root=campaign_root,
                contracts=contracts,
                official_src=official_src,
                upstream_commit=upstream_commit,
                variant_directories=found,
            )
        )
    output.mkdir(parents=True, exist_ok=True)
    written = []
    for payload in payloads:
        path = output / "{}.json".format(payload["case_id"])
        path.write_text(render_case_file(payload), encoding="utf-8")
        written.append(path)
    sensitivity = build_sensitivity_payloads(
        band_sampling,
        {str(payload["case_id"]): payload for payload in payloads},
        upstream_commit,
    )
    if sensitivity:
        sensitivity_directory = output / SENSITIVITY_DIRECTORY_NAME
        sensitivity_directory.mkdir(parents=True, exist_ok=True)
        for case_id, payload in sensitivity.items():
            path = sensitivity_directory / f"{case_id}.json"
            path.write_text(render_case_file(payload), encoding="utf-8")
            written.append(path)
    readme = output / "README.md"
    readme.write_text(render_readme(payloads, upstream_commit), encoding="utf-8")
    written.append(readme)
    return tuple(sorted(written))


def parse_variant(argument: str) -> tuple[str, str]:
    """``name=capture-directory-name``."""
    name, separator, directory_name = argument.partition("=")
    if not separator or not name or not directory_name:
        raise argparse.ArgumentTypeError(
            f"expected name=capture-directory-name, got {argument!r}"
        )
    if name == CANONICAL_VARIANT:
        raise argparse.ArgumentTypeError(
            f"{CANONICAL_VARIANT!r} is the top-level record and cannot be redefined as a variant"
        )
    return name, directory_name


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--campaign-root",
        type=Path,
        required=True,
        help="root holding claude/runs and reference-simple/runs",
    )
    parser.add_argument(
        "--manifest", type=Path, required=True, help="examples/jax/manifest.json"
    )
    parser.add_argument(
        "--official-src",
        type=Path,
        required=True,
        help="official simsopt clone source root",
    )
    parser.add_argument(
        "--upstream-commit", required=True, help="full 40-hex upstream commit"
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="directory to write the fixture files into",
    )
    parser.add_argument(
        "--band-sampling",
        type=Path,
        default=None,
        help=(
            "directory of the band-sampling investigation whose per-run artefacts become the sensitivity records "
            "(default: <campaign-root>/investigations/band-sampling; skipped when that directory has no "
            f"{SENSITIVITY_SUMMARY_NAME})"
        ),
    )
    parser.add_argument(
        "--variant",
        dest="variants",
        type=parse_variant,
        action="append",
        default=None,
        metavar="NAME=DIRECTORY",
        help=(
            "extra captured run to record under the optional 'variants' key, repeatable "
            f"(default: {', '.join(f'{k}={v}' for k, v in VARIANT_DIRECTORY_NAMES.items())})"
        ),
    )
    parser.add_argument(
        "--contracts",
        type=Path,
        default=None,
        help="directory of native-<case_id>.json contracts (default: <campaign-root>/claude/contracts)",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    contracts = (
        args.contracts
        if args.contracts is not None
        else args.campaign_root / "claude" / "contracts"
    )
    written = write_official_reference(
        campaign_root=args.campaign_root,
        manifest=args.manifest,
        contracts=contracts,
        official_src=args.official_src,
        upstream_commit=args.upstream_commit,
        output=args.output,
        band_sampling=(
            args.band_sampling
            if args.band_sampling is not None
            else args.campaign_root / "investigations" / "band-sampling"
        ),
        variants=(
            VARIANT_DIRECTORY_NAMES if args.variants is None else dict(args.variants)
        ),
    )
    print(f"wrote {len(written)} files to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
