"""Typed JAX optimizer API for SIMSOPT solve drivers."""

from ._dispatch import least_squares, minimize
from .contracts import (
    Driver,
    OptimizerCallbackEvent,
    OptimizerResult,
    OptimizerResultFingerprint,
    OptionsBase,
    STATUS_CODES,
    OptaxAdamCallbackEvent,
    OptaxLBFGSCallbackEvent,
    ScipyBFGSCallbackEvent,
    ScipyLBFGSBCallbackEvent,
    SimsoptAdamCallbackEvent,
    SimsoptAdamHostCallbackEvent,
    SimsoptBFGSCallbackEvent,
    SimsoptLBFGSBCallbackEvent,
    SimsoptLMGMRESCallbackEvent,
    SimsoptLMGMRESHostCallbackEvent,
    SimsoptLMQRCallbackEvent,
    SimsoptTraceLBFGSCallbackEvent,
    fingerprint_optimizer_result,
)
from .optimistix import LinearSolver, OptimistixLMOptions
from .optax import OptaxAdamOptions, OptaxLBFGSOptions, OptaxLineSearch
from .scipy import ScipyBFGSOptions, ScipyLBFGSBOptions, ScipyLMOptions
from .simsopt import (
    SimsoptAdamHostOptions,
    SimsoptAdamOptions,
    SimsoptBFGSOptions,
    SimsoptLBFGSBOptions,
    SimsoptLMGMRESHostOptions,
    SimsoptLMGMRESOptions,
    SimsoptLMQROptions,
    SimsoptTraceLBFGSOptions,
)

__all__ = [
    "Driver",
    "LinearSolver",
    "OptaxAdamOptions",
    "OptaxAdamCallbackEvent",
    "OptaxLBFGSOptions",
    "OptaxLBFGSCallbackEvent",
    "OptaxLineSearch",
    "OptimizerCallbackEvent",
    "OptimizerResult",
    "OptimizerResultFingerprint",
    "OptimistixLMOptions",
    "OptionsBase",
    "STATUS_CODES",
    "ScipyBFGSOptions",
    "ScipyBFGSCallbackEvent",
    "ScipyLBFGSBOptions",
    "ScipyLBFGSBCallbackEvent",
    "ScipyLMOptions",
    "SimsoptAdamHostOptions",
    "SimsoptAdamHostCallbackEvent",
    "SimsoptAdamOptions",
    "SimsoptAdamCallbackEvent",
    "SimsoptBFGSOptions",
    "SimsoptBFGSCallbackEvent",
    "SimsoptLBFGSBOptions",
    "SimsoptLBFGSBCallbackEvent",
    "SimsoptLMGMRESHostOptions",
    "SimsoptLMGMRESHostCallbackEvent",
    "SimsoptLMGMRESOptions",
    "SimsoptLMGMRESCallbackEvent",
    "SimsoptLMQROptions",
    "SimsoptLMQRCallbackEvent",
    "SimsoptTraceLBFGSOptions",
    "SimsoptTraceLBFGSCallbackEvent",
    "fingerprint_optimizer_result",
    "least_squares",
    "minimize",
]
