"""Pure JAX kernel-layer specs and helpers."""

from importlib import import_module

__all__ = [
    "BiotSavartSpec",
    "build_filament_gamma_and_dash",
    "build_filament_gammas",
    "centroid_frame",
    "centroid_frame_dash",
    "compute_filament_offsets",
    "frenet_frame",
    "frenet_frame_dash",
    "rotated_centroid_frame",
    "rotated_centroid_frame_dash",
    "rotated_frenet_frame",
    "rotated_frenet_frame_dash",
    "rotation_alpha",
    "rotation_alphadash",
    "rotation_dcoeff",
    "rotationdash_dcoeff",
    "CoilSpec",
    "CoilGroupSpec",
    "CoilDofExtractionSpec",
    "CoilSetDofExtractionSpec",
    "CoilSymmetrySpec",
    "apply_coil_symmetry",
    "CurveCWSFourierRZSpec",
    "CurveFilamentSpec",
    "CurveHelicalSpec",
    "OrientedCurveXYZFourierSpec",
    "make_oriented_curve_xyzfourier_spec",
    "CurvePlanarFourierSpec",
    "CurveSpec",
    "CurveSpecKind",
    "CurvePerturbedSpec",
    "CurrentValueSpec",
    "CurveRZFourierSpec",
    "CurveXYZFourierSpec",
    "CurveXYZFourierSymmetriesSpec",
    "FieldEvalSpec",
    "FrameRotationSpec",
    "FixedSurfaceFluxSpec",
    "GroupedCoilSetSpec",
    "OptimizableDofMapSpec",
    "RotationSpec",
    "SingleStageRuntimeSpec",
    "SingleStageSeedSpec",
    "SurfaceGarabedianSpec",
    "SurfaceHennebergSpec",
    "SurfaceRZFourierSpec",
    "SurfaceSpec",
    "SurfaceSpecKind",
    "SurfaceXYZFourierSpec",
    "SurfaceXYZTensorFourierSpec",
    "ZeroRotationSpec",
    "build_fourier_basis",
    "closed_curve_self_intersection_min_distance",
    "closed_curve_self_intersection_penalty",
    "closed_curve_self_intersection_summary",
    "closed_curve_self_intersection_tolerance",
    "curve_dincremental_arclength_by_dcoeff_from_dofs",
    "curve_dincremental_arclength_by_dcoeff_vjp_from_dofs",
    "curve_dkappa_by_dcoeff_from_dofs",
    "curve_dkappa_by_dcoeff_vjp_from_dofs",
    "curve_dtorsion_by_dcoeff_from_dofs",
    "curve_dtorsion_by_dcoeff_vjp_from_dofs",
    "curve_gamma_and_dash_from_dofs",
    "curve_gamma_and_dash_from_spec",
    "curve_gamma_vjp_from_dofs",
    "curve_geometry_from_dofs",
    "curve_geometry_from_spec",
    "curve_gammadash_vjp_from_dofs",
    "curve_gammadashdash_vjp_from_dofs",
    "curve_gammadashdashdash_vjp_from_dofs",
    "curve_incremental_arclength_from_dofs",
    "curve_incremental_arclength_from_spec",
    "curve_kappa_from_dofs",
    "curve_kappa_from_spec",
    "curve_pullback_from_dofs",
    "curve_pullback_from_spec",
    "curve_spec_kind",
    "surface_spec_kind",
    "curve_spec_from_curve",
    "curve_spec_with_dofs",
    "curve_spec_with_quadpoints",
    "curve_torsion_from_dofs",
    "curve_torsion_from_spec",
    "coil_set_spec_from_dof_extraction_spec",
    "coil_specs_from_dof_extraction_spec",
    "CircularCoilSpec",
    "circular_coil_A",
    "circular_coil_B",
    "circular_coil_dB",
    "biot_savart_A",
    "biot_savart_B",
    "biot_savart_B_and_dB",
    "biot_savart_B_vjp",
    "biot_savart_dA_by_dX",
    "biot_savart_dB_by_dX",
    "group_coil_data",
    "grouped_biot_savart_A",
    "grouped_biot_savart_B",
    "invalidate_kernel_cache",
    "FLUX_FUNCTION_SCALARS",
    "InterpolatedBoozerFieldFrozenState",
    "SYMMETRY_EXPLOIT_SCALARS",
    "build_flux_function_interpolant",
    "build_symmetry_exploit_interpolant",
    "evaluate_interpolated_boozer_scalar",
    "fold_points_for_symmetry",
    "freeze_interpolated_boozer_field_state",
    "fixed_surface_flux_specs_from_surface",
    "fixed_surface_flux_integral",
    "fixed_surface_flux_integral_from_B",
    "VALID_REDUCTION_MODES",
    "compensated_sum_flat",
    "pairwise_sum_axis",
    "pairwise_sum_flat",
    "scalar_square_sum",
    "validate_reduction_mode",
    "boozer_quasisymmetry_mode_indices",
    "boozer_quasisymmetry_residuals",
    "iota_target_metric_j",
    "iota_weighted_j",
    "well_weighted_j",
    "grouped_coil_set_spec_from_coil_specs",
    "grouped_biot_savart_A_from_inputs",
    "grouped_biot_savart_A_from_spec",
    "grouped_biot_savart_B_and_dB_from_spec",
    "grouped_biot_savart_B_from_inputs",
    "grouped_biot_savart_B_from_spec",
    "grouped_biot_savart_d2A_by_dXdX_from_inputs",
    "grouped_biot_savart_d2A_by_dXdX_from_spec",
    "grouped_biot_savart_d2B_by_dXdX_from_inputs",
    "grouped_biot_savart_d2B_by_dXdX_from_spec",
    "grouped_biot_savart_dA_by_dX_from_inputs",
    "grouped_biot_savart_dA_by_dX_from_spec",
    "grouped_biot_savart_dB_by_dX_from_inputs",
    "grouped_biot_savart_dB_by_dX_from_spec",
    "grouped_coil_currents_from_inputs",
    "grouped_coil_currents_from_spec",
    "grouped_coil_index_lists_from_spec",
    "grouped_coil_set_spec_from_grouped_data",
    "grouped_coil_set_spec_from_inputs",
    "grouped_coil_set_spec_from_lists",
    "grouped_coil_set_spec_from_source",
    "grouped_field_data_from_spec",
    "grouped_field_inputs_from_spec",
    "make_biot_savart_spec",
    "make_coil_spec",
    "make_coil_dof_extraction_spec",
    "make_coil_symmetry_spec",
    "make_coil_group_spec",
    "make_coil_set_dof_extraction_spec",
    "make_current_value_spec",
    "make_curve_cwsfourier_rz_spec",
    "make_curve_filament_spec",
    "make_curve_helical_spec",
    "make_curve_planarfourier_spec",
    "make_curve_perturbed_spec",
    "make_curve_rzfourier_spec",
    "make_curve_xyzfourier_spec",
    "make_curve_xyzfouriersymmetries_spec",
    "make_field_eval_spec",
    "make_frame_rotation_spec",
    "make_fixed_surface_flux_spec",
    "make_grouped_coil_set_spec",
    "make_optimizable_dof_map_spec",
    "make_single_stage_runtime_spec",
    "make_single_stage_seed_spec",
    "make_surface_garabedian_spec",
    "make_surface_henneberg_spec",
    "make_surface_rzfourier_spec",
    "make_zero_rotation_spec",
    "garabedian_to_rzfourier_spec",
    "pair_linking_number_pure",
    "segment_segment_distance_pure",
    "surface_rz_fourier_aspect_ratio_from_spec",
    "surface_rz_fourier_aspect_ratio_from_dofs",
    "surface_rz_fourier_area_from_spec",
    "surface_rz_fourier_area_from_dofs",
    "surface_rz_fourier_d2area_from_dofs",
    "surface_rz_fourier_d2aspect_ratio_from_dofs",
    "surface_rz_fourier_d2major_radius_from_dofs",
    "surface_rz_fourier_d2minor_radius_from_dofs",
    "surface_rz_fourier_d2volume_from_dofs",
    "surface_rz_fourier_darea_from_dofs",
    "surface_rz_fourier_daspect_ratio_from_dofs",
    "surface_rz_fourier_dfirst_fund_form_from_dofs",
    "surface_rz_fourier_dofs_from_spec",
    "surface_rz_fourier_dmajor_radius_from_dofs",
    "surface_rz_fourier_dmean_cross_sectional_area_from_dofs",
    "surface_rz_fourier_dminor_radius_from_dofs",
    "surface_rz_fourier_dsecond_fund_form_from_dofs",
    "surface_rz_fourier_dsurface_curvatures_from_dofs",
    "surface_rz_fourier_dvolume_from_dofs",
    "surface_rz_fourier_first_fund_form_from_spec",
    "surface_rz_fourier_first_fund_form_from_dofs",
    "surface_rz_fourier_gamma_from_spec",
    "surface_rz_fourier_gamma_from_dofs",
    "surface_rz_fourier_gammadash1dash1_from_spec",
    "surface_rz_fourier_gammadash1dash1_from_dofs",
    "surface_rz_fourier_gammadash1dash1dash1_lin_from_spec",
    "surface_rz_fourier_gammadash1dash1dash1_lin_from_dofs",
    "surface_rz_fourier_gammadash1dash1_vjp_from_dofs",
    "surface_rz_fourier_gammadash1dash2_from_spec",
    "surface_rz_fourier_gammadash1dash2_from_dofs",
    "surface_rz_fourier_gammadash1dash1dash2_lin_from_spec",
    "surface_rz_fourier_gammadash1dash1dash2_lin_from_dofs",
    "surface_rz_fourier_gammadash1dash2dash2_lin_from_spec",
    "surface_rz_fourier_gammadash1dash2dash2_lin_from_dofs",
    "surface_rz_fourier_gammadash1dash2_vjp_from_dofs",
    "surface_rz_fourier_gammadash1_from_spec",
    "surface_rz_fourier_gammadash1_from_dofs",
    "surface_rz_fourier_gammadash2dash2_from_spec",
    "surface_rz_fourier_gammadash2dash2_from_dofs",
    "surface_rz_fourier_gammadash2dash2dash2_lin_from_spec",
    "surface_rz_fourier_gammadash2dash2dash2_lin_from_dofs",
    "surface_rz_fourier_gammadash2dash2_vjp_from_dofs",
    "surface_rz_fourier_gammadash2_from_spec",
    "surface_rz_fourier_gammadash2_from_dofs",
    "surface_rz_fourier_major_radius_from_spec",
    "surface_rz_fourier_major_radius_from_dofs",
    "surface_rz_fourier_mean_cross_sectional_area_from_spec",
    "surface_rz_fourier_mean_cross_sectional_area_from_dofs",
    "surface_rz_fourier_minor_radius_from_spec",
    "surface_rz_fourier_minor_radius_from_dofs",
    "surface_rz_fourier_normal_from_spec",
    "surface_rz_fourier_normal_from_dofs",
    "surface_rz_fourier_second_fund_form_from_spec",
    "surface_rz_fourier_second_fund_form_from_dofs",
    "surface_rz_fourier_dgammadash1dash1_from_dofs",
    "surface_rz_fourier_dgammadash1dash2_from_dofs",
    "surface_rz_fourier_dgammadash2dash2_from_dofs",
    "surface_rz_fourier_dnormal_from_dofs",
    "surface_rz_fourier_spec_from_dofs",
    "surface_rz_fourier_surface_curvatures_from_spec",
    "surface_rz_fourier_surface_curvatures_from_dofs",
    "surface_rz_fourier_unitnormal_from_spec",
    "surface_rz_fourier_unitnormal_from_dofs",
    "surface_rz_fourier_dunitnormal_from_dofs",
    "surface_rz_fourier_volume_from_spec",
    "surface_rz_fourier_volume_from_dofs",
    "surface_xyz_fourier_area_from_spec",
    "surface_xyz_fourier_dfirst_fund_form_from_dofs",
    "surface_xyz_fourier_dsecond_fund_form_from_dofs",
    "surface_xyz_fourier_dsurface_curvatures_from_dofs",
    "surface_xyz_fourier_first_fund_form_from_spec",
    "surface_xyz_fourier_first_fund_form_from_dofs",
    "surface_xyz_fourier_gamma_from_spec",
    "surface_xyz_fourier_gammadash1_from_spec",
    "surface_xyz_fourier_gammadash1dash1_from_spec",
    "surface_xyz_fourier_gammadash1dash1_lin_from_spec",
    "surface_xyz_fourier_gammadash1dash1_lin_from_dofs",
    "surface_xyz_fourier_gammadash1dash1dash1_lin_from_spec",
    "surface_xyz_fourier_gammadash1dash1dash1_lin_from_dofs",
    "surface_xyz_fourier_gammadash1dash1dash2_lin_from_spec",
    "surface_xyz_fourier_gammadash1dash1dash2_lin_from_dofs",
    "surface_xyz_fourier_gammadash1dash2_from_spec",
    "surface_xyz_fourier_gammadash1dash2_lin_from_spec",
    "surface_xyz_fourier_gammadash1dash2_lin_from_dofs",
    "surface_xyz_fourier_gammadash1dash2dash2_lin_from_spec",
    "surface_xyz_fourier_gammadash1dash2dash2_lin_from_dofs",
    "surface_xyz_fourier_gammadash2_from_spec",
    "surface_xyz_fourier_gammadash2dash2_from_spec",
    "surface_xyz_fourier_gammadash2dash2_lin_from_spec",
    "surface_xyz_fourier_gammadash2dash2_lin_from_dofs",
    "surface_xyz_fourier_gammadash2dash2dash2_lin_from_spec",
    "surface_xyz_fourier_gammadash2dash2dash2_lin_from_dofs",
    "surface_xyz_fourier_normal_from_spec",
    "surface_xyz_fourier_second_fund_form_from_spec",
    "surface_xyz_fourier_second_fund_form_from_dofs",
    "surface_xyz_fourier_surface_curvatures_from_spec",
    "surface_xyz_fourier_surface_curvatures_from_dofs",
    "surface_xyz_fourier_unitnormal_from_spec",
    "surface_xyz_fourier_volume_from_spec",
    "surface_henneberg_area_from_spec",
    "surface_henneberg_gamma_from_spec",
    "surface_henneberg_gammadash1_from_spec",
    "surface_henneberg_gammadash2_from_spec",
    "surface_henneberg_normal_from_spec",
    "surface_henneberg_unitnormal_from_spec",
    "surface_henneberg_volume_from_spec",
    "surface_xyz_tensor_fourier_area_from_spec",
    "surface_xyz_tensor_fourier_dfirst_fund_form_from_dofs",
    "surface_xyz_tensor_fourier_dsecond_fund_form_from_dofs",
    "surface_xyz_tensor_fourier_dsurface_curvatures_from_dofs",
    "surface_xyz_tensor_fourier_first_fund_form_from_spec",
    "surface_xyz_tensor_fourier_first_fund_form_from_dofs",
    "surface_xyz_tensor_fourier_gamma_from_spec",
    "surface_xyz_tensor_fourier_gammadash1_from_spec",
    "surface_xyz_tensor_fourier_gammadash1dash1_from_spec",
    "surface_xyz_tensor_fourier_gammadash1dash1_lin_from_spec",
    "surface_xyz_tensor_fourier_gammadash1dash1_lin_from_dofs",
    "surface_xyz_tensor_fourier_gammadash1dash1dash1_lin_from_spec",
    "surface_xyz_tensor_fourier_gammadash1dash1dash1_lin_from_dofs",
    "surface_xyz_tensor_fourier_gammadash1dash1dash2_lin_from_spec",
    "surface_xyz_tensor_fourier_gammadash1dash1dash2_lin_from_dofs",
    "surface_xyz_tensor_fourier_gammadash1dash2_from_spec",
    "surface_xyz_tensor_fourier_gammadash1dash2_lin_from_spec",
    "surface_xyz_tensor_fourier_gammadash1dash2_lin_from_dofs",
    "surface_xyz_tensor_fourier_gammadash1dash2dash2_lin_from_spec",
    "surface_xyz_tensor_fourier_gammadash1dash2dash2_lin_from_dofs",
    "surface_xyz_tensor_fourier_gammadash2_from_spec",
    "surface_xyz_tensor_fourier_gammadash2dash2_from_spec",
    "surface_xyz_tensor_fourier_gammadash2dash2_lin_from_spec",
    "surface_xyz_tensor_fourier_gammadash2dash2_lin_from_dofs",
    "surface_xyz_tensor_fourier_gammadash2dash2dash2_lin_from_spec",
    "surface_xyz_tensor_fourier_gammadash2dash2dash2_lin_from_dofs",
    "surface_xyz_tensor_fourier_normal_from_spec",
    "surface_xyz_tensor_fourier_second_fund_form_from_spec",
    "surface_xyz_tensor_fourier_second_fund_form_from_dofs",
    "surface_xyz_tensor_fourier_surface_curvatures_from_spec",
    "surface_xyz_tensor_fourier_surface_curvatures_from_dofs",
    "surface_xyz_tensor_fourier_unitnormal_from_spec",
    "surface_xyz_tensor_fourier_volume_from_spec",
    "make_surface_xyz_fourier_spec",
    "make_surface_xyz_tensor_fourier_spec",
]

_EXPORT_MODULES = {
    "BiotSavartSpec": "specs",
    "build_filament_gamma_and_dash": "finitebuild",
    "build_filament_gammas": "finitebuild",
    "centroid_frame": "framedcurve",
    "centroid_frame_dash": "framedcurve",
    "compute_filament_offsets": "finitebuild",
    "frenet_frame": "framedcurve",
    "frenet_frame_dash": "framedcurve",
    "rotated_centroid_frame": "framedcurve",
    "rotated_centroid_frame_dash": "framedcurve",
    "rotated_frenet_frame": "framedcurve",
    "rotated_frenet_frame_dash": "framedcurve",
    "rotation_alpha": "framedcurve",
    "rotation_alphadash": "framedcurve",
    "rotation_dcoeff": "framedcurve",
    "rotationdash_dcoeff": "framedcurve",
    "CoilSpec": "specs",
    "CoilGroupSpec": "specs",
    "CoilDofExtractionSpec": "specs",
    "CoilSetDofExtractionSpec": "specs",
    "CoilSymmetrySpec": "specs",
    "apply_coil_symmetry": "specs",
    "CurveCWSFourierRZSpec": "specs",
    "CurveFilamentSpec": "specs",
    "CurveHelicalSpec": "specs",
    "OrientedCurveXYZFourierSpec": "specs",
    "make_oriented_curve_xyzfourier_spec": "specs",
    "CurvePlanarFourierSpec": "specs",
    "CurveSpec": "specs",
    "CurveSpecKind": "specs",
    "CurvePerturbedSpec": "specs",
    "CurrentValueSpec": "specs",
    "CurveRZFourierSpec": "specs",
    "CurveXYZFourierSpec": "specs",
    "CurveXYZFourierSymmetriesSpec": "specs",
    "FieldEvalSpec": "specs",
    "FrameRotationSpec": "specs",
    "FixedSurfaceFluxSpec": "specs",
    "GroupedCoilSetSpec": "specs",
    "OptimizableDofMapSpec": "specs",
    "RotationSpec": "specs",
    "SingleStageRuntimeSpec": "specs",
    "SingleStageSeedSpec": "specs",
    "SurfaceGarabedianSpec": "specs",
    "SurfaceHennebergSpec": "specs",
    "SurfaceRZFourierSpec": "specs",
    "SurfaceSpec": "specs",
    "SurfaceSpecKind": "specs",
    "SurfaceXYZFourierSpec": "specs",
    "SurfaceXYZTensorFourierSpec": "specs",
    "ZeroRotationSpec": "specs",
    "build_fourier_basis": "objectives_flux",
    "closed_curve_self_intersection_min_distance": "curve_geometry",
    "closed_curve_self_intersection_penalty": "curve_geometry",
    "closed_curve_self_intersection_summary": "curve_geometry",
    "closed_curve_self_intersection_tolerance": "curve_geometry",
    "curve_dincremental_arclength_by_dcoeff_from_dofs": "curve_geometry",
    "curve_dincremental_arclength_by_dcoeff_vjp_from_dofs": "curve_geometry",
    "curve_dkappa_by_dcoeff_from_dofs": "curve_geometry",
    "curve_dkappa_by_dcoeff_vjp_from_dofs": "curve_geometry",
    "curve_dtorsion_by_dcoeff_from_dofs": "curve_geometry",
    "curve_dtorsion_by_dcoeff_vjp_from_dofs": "curve_geometry",
    "curve_gamma_and_dash_from_dofs": "curve_geometry",
    "curve_gamma_and_dash_from_spec": "curve_geometry",
    "curve_gamma_vjp_from_dofs": "curve_geometry",
    "curve_geometry_from_dofs": "curve_geometry",
    "curve_geometry_from_spec": "curve_geometry",
    "curve_gammadash_vjp_from_dofs": "curve_geometry",
    "curve_gammadashdash_vjp_from_dofs": "curve_geometry",
    "curve_gammadashdashdash_vjp_from_dofs": "curve_geometry",
    "curve_incremental_arclength_from_dofs": "curve_geometry",
    "curve_incremental_arclength_from_spec": "curve_geometry",
    "curve_kappa_from_dofs": "curve_geometry",
    "curve_kappa_from_spec": "curve_geometry",
    "curve_pullback_from_dofs": "curve_geometry",
    "curve_pullback_from_spec": "curve_geometry",
    "curve_spec_kind": "specs",
    "surface_spec_kind": "specs",
    "curve_spec_from_curve": "curve_geometry",
    "curve_spec_with_dofs": "curve_geometry",
    "curve_spec_with_quadpoints": "curve_geometry",
    "curve_torsion_from_dofs": "curve_geometry",
    "curve_torsion_from_spec": "curve_geometry",
    "coil_set_spec_from_dof_extraction_spec": "field",
    "coil_specs_from_dof_extraction_spec": "field",
    "CircularCoilSpec": "circular_coil",
    "circular_coil_A": "circular_coil",
    "circular_coil_B": "circular_coil",
    "circular_coil_dB": "circular_coil",
    "biot_savart_A": "biotsavart",
    "biot_savart_B": "biotsavart",
    "biot_savart_B_and_dB": "biotsavart",
    "biot_savart_B_vjp": "biotsavart",
    "biot_savart_dA_by_dX": "biotsavart",
    "biot_savart_dB_by_dX": "biotsavart",
    "group_coil_data": "biotsavart",
    "grouped_biot_savart_A": "biotsavart",
    "grouped_biot_savart_B": "biotsavart",
    "invalidate_kernel_cache": "biotsavart",
    "FLUX_FUNCTION_SCALARS": "interpolated_boozer_field",
    "InterpolatedBoozerFieldFrozenState": "interpolated_boozer_field",
    "SYMMETRY_EXPLOIT_SCALARS": "interpolated_boozer_field",
    "build_flux_function_interpolant": "interpolated_boozer_field",
    "build_symmetry_exploit_interpolant": "interpolated_boozer_field",
    "evaluate_interpolated_boozer_scalar": "interpolated_boozer_field",
    "fold_points_for_symmetry": "interpolated_boozer_field",
    "freeze_interpolated_boozer_field_state": "interpolated_boozer_field",
    "fixed_surface_flux_specs_from_surface": "objectives_flux",
    "fixed_surface_flux_integral": "objectives_flux",
    "fixed_surface_flux_integral_from_B": "objectives_flux",
    "VALID_REDUCTION_MODES": "reductions",
    "compensated_sum_flat": "reductions",
    "pairwise_sum_axis": "reductions",
    "pairwise_sum_flat": "reductions",
    "scalar_square_sum": "reductions",
    "validate_reduction_mode": "reductions",
    "boozer_quasisymmetry_mode_indices": "mhd_reductions",
    "boozer_quasisymmetry_residuals": "mhd_reductions",
    "iota_target_metric_j": "mhd_reductions",
    "iota_weighted_j": "mhd_reductions",
    "well_weighted_j": "mhd_reductions",
    "grouped_coil_set_spec_from_coil_specs": "field",
    "grouped_biot_savart_A_from_inputs": "field",
    "grouped_biot_savart_A_from_spec": "field",
    "grouped_biot_savart_B_and_dB_from_spec": "field",
    "grouped_biot_savart_B_from_inputs": "field",
    "grouped_biot_savart_B_from_spec": "field",
    "grouped_biot_savart_d2A_by_dXdX_from_inputs": "field",
    "grouped_biot_savart_d2A_by_dXdX_from_spec": "field",
    "grouped_biot_savart_d2B_by_dXdX_from_inputs": "field",
    "grouped_biot_savart_d2B_by_dXdX_from_spec": "field",
    "grouped_biot_savart_dA_by_dX_from_inputs": "field",
    "grouped_biot_savart_dA_by_dX_from_spec": "field",
    "grouped_biot_savart_dB_by_dX_from_inputs": "field",
    "grouped_biot_savart_dB_by_dX_from_spec": "field",
    "grouped_coil_currents_from_inputs": "field",
    "grouped_coil_currents_from_spec": "field",
    "grouped_coil_index_lists_from_spec": "field",
    "grouped_coil_set_spec_from_grouped_data": "field",
    "grouped_coil_set_spec_from_inputs": "field",
    "grouped_coil_set_spec_from_lists": "field",
    "grouped_coil_set_spec_from_source": "field",
    "grouped_field_data_from_spec": "field",
    "grouped_field_inputs_from_spec": "field",
    "make_biot_savart_spec": "specs",
    "make_coil_spec": "specs",
    "make_coil_dof_extraction_spec": "specs",
    "make_coil_symmetry_spec": "specs",
    "make_coil_group_spec": "specs",
    "make_coil_set_dof_extraction_spec": "specs",
    "make_current_value_spec": "specs",
    "make_curve_cwsfourier_rz_spec": "specs",
    "make_curve_filament_spec": "specs",
    "make_curve_helical_spec": "specs",
    "make_curve_planarfourier_spec": "specs",
    "make_curve_perturbed_spec": "specs",
    "make_curve_rzfourier_spec": "specs",
    "make_curve_xyzfourier_spec": "specs",
    "make_curve_xyzfouriersymmetries_spec": "specs",
    "make_field_eval_spec": "specs",
    "make_frame_rotation_spec": "specs",
    "make_fixed_surface_flux_spec": "specs",
    "make_grouped_coil_set_spec": "specs",
    "make_optimizable_dof_map_spec": "specs",
    "make_single_stage_runtime_spec": "specs",
    "make_single_stage_seed_spec": "specs",
    "make_surface_garabedian_spec": "specs",
    "make_surface_henneberg_spec": "specs",
    "make_surface_rzfourier_spec": "specs",
    "make_zero_rotation_spec": "specs",
    "garabedian_to_rzfourier_spec": "specs",
    "pair_linking_number_pure": "curve_geometry",
    "segment_segment_distance_pure": "curve_geometry",
    "surface_rz_fourier_aspect_ratio_from_spec": "surface_rzfourier",
    "surface_rz_fourier_aspect_ratio_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_area_from_spec": "surface_rzfourier",
    "surface_rz_fourier_area_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_d2area_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_d2aspect_ratio_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_d2major_radius_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_d2minor_radius_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_d2volume_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_darea_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_daspect_ratio_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dfirst_fund_form_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dofs_from_spec": "surface_rzfourier",
    "surface_rz_fourier_dmajor_radius_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dmean_cross_sectional_area_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dminor_radius_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dsecond_fund_form_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dsurface_curvatures_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dvolume_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_first_fund_form_from_spec": "surface_rzfourier",
    "surface_rz_fourier_first_fund_form_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gamma_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gamma_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash1_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash1_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash1dash1_lin_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash1dash1_lin_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash1_vjp_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash2_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash2_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash1dash2_lin_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash1dash2_lin_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash2dash2_lin_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash2dash2_lin_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash1dash2_vjp_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash1_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash1_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash2dash2_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash2dash2_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash2dash2dash2_lin_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash2dash2dash2_lin_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash2dash2_vjp_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_gammadash2_from_spec": "surface_rzfourier",
    "surface_rz_fourier_gammadash2_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_major_radius_from_spec": "surface_rzfourier",
    "surface_rz_fourier_major_radius_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_mean_cross_sectional_area_from_spec": "surface_rzfourier",
    "surface_rz_fourier_mean_cross_sectional_area_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_minor_radius_from_spec": "surface_rzfourier",
    "surface_rz_fourier_minor_radius_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_normal_from_spec": "surface_rzfourier",
    "surface_rz_fourier_normal_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_second_fund_form_from_spec": "surface_rzfourier",
    "surface_rz_fourier_second_fund_form_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dgammadash1dash1_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dgammadash1dash2_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dgammadash2dash2_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dnormal_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_spec_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_surface_curvatures_from_spec": "surface_rzfourier",
    "surface_rz_fourier_surface_curvatures_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_unitnormal_from_spec": "surface_rzfourier",
    "surface_rz_fourier_unitnormal_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_dunitnormal_from_dofs": "surface_rzfourier",
    "surface_rz_fourier_volume_from_spec": "surface_rzfourier",
    "surface_rz_fourier_volume_from_dofs": "surface_rzfourier",
    "surface_xyz_fourier_area_from_spec": "surface_fourier",
    "surface_xyz_fourier_dfirst_fund_form_from_dofs": "surface_fourier",
    "surface_xyz_fourier_dsecond_fund_form_from_dofs": "surface_fourier",
    "surface_xyz_fourier_dsurface_curvatures_from_dofs": "surface_fourier",
    "surface_xyz_fourier_first_fund_form_from_spec": "surface_fourier",
    "surface_xyz_fourier_first_fund_form_from_dofs": "surface_fourier",
    "surface_xyz_fourier_gamma_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash1_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash1_lin_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash1_lin_from_dofs": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash1dash1_lin_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash1dash1_lin_from_dofs": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash1dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash1dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash2_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash2dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash1dash2dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_fourier_gammadash2_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash2dash2_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash2dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash2dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_fourier_gammadash2dash2dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_fourier_gammadash2dash2dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_fourier_normal_from_spec": "surface_fourier",
    "surface_xyz_fourier_second_fund_form_from_spec": "surface_fourier",
    "surface_xyz_fourier_second_fund_form_from_dofs": "surface_fourier",
    "surface_xyz_fourier_surface_curvatures_from_spec": "surface_fourier",
    "surface_xyz_fourier_surface_curvatures_from_dofs": "surface_fourier",
    "surface_xyz_fourier_unitnormal_from_spec": "surface_fourier",
    "surface_xyz_fourier_volume_from_spec": "surface_fourier",
    "surface_henneberg_area_from_spec": "surface_henneberg",
    "surface_henneberg_gamma_from_spec": "surface_henneberg",
    "surface_henneberg_gammadash1_from_spec": "surface_henneberg",
    "surface_henneberg_gammadash2_from_spec": "surface_henneberg",
    "surface_henneberg_normal_from_spec": "surface_henneberg",
    "surface_henneberg_unitnormal_from_spec": "surface_henneberg",
    "surface_henneberg_volume_from_spec": "surface_henneberg",
    "surface_xyz_tensor_fourier_area_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_dfirst_fund_form_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_dsecond_fund_form_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_dsurface_curvatures_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_first_fund_form_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_first_fund_form_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_gamma_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash1_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash1_lin_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash1_lin_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash1dash1_lin_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash1dash1_lin_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash1dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash1dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash2_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash2dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash1dash2dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash2_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash2dash2_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash2dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash2dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash2dash2dash2_lin_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_gammadash2dash2dash2_lin_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_normal_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_second_fund_form_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_second_fund_form_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_surface_curvatures_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_surface_curvatures_from_dofs": "surface_fourier",
    "surface_xyz_tensor_fourier_unitnormal_from_spec": "surface_fourier",
    "surface_xyz_tensor_fourier_volume_from_spec": "surface_fourier",
    "make_surface_xyz_fourier_spec": "specs",
    "make_surface_xyz_tensor_fourier_spec": "specs",
}


def __getattr__(name):
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f".{module_name}", __name__), name)
    globals()[name] = value
    return value
