"""Typed lightweight contracts for SIMSOPT JAX solve drivers."""

from .contracts import (
    Driver,
    HessianInverse,
    InverseHessianOperator,
    LbfgsbRestartEvent,
    LbfgsbRestartReason,
    NONFINITE_RESULT_STATUS,
    OptimizerCallbackEvent,
    OptimizerResult,
    OptimizerResultFingerprint,
    OptionsBase,
    SCIPY_LBFGSB_UNRESOLVED_STALL_STATUS,
    STATUS_CODES,
    ScipyBFGSCallbackEvent,
    ScipyLBFGSBCallbackEvent,
    SimsoptAdamCallbackEvent,
    SimsoptAdamHostCallbackEvent,
    SimsoptBFGSCallbackEvent,
    SimsoptLBFGSBCallbackEvent,
    SimsoptLMQRCallbackEvent,
    SimsoptTraceLBFGSCallbackEvent,
    fingerprint_optimizer_result,
)
from .scipy import ScipyBFGSOptions, ScipyBounds, ScipyLBFGSBOptions, ScipyLMOptions
from .simsopt import (
    SimsoptAdamHostOptions,
    SimsoptAdamOptions,
    SimsoptBFGSOptions,
    SimsoptLBFGSBOptions,
    SimsoptLMQROptions,
    SimsoptTraceLBFGSOptions,
)

__all__ = [
    "Driver",
    "HessianInverse",
    "InverseHessianOperator",
    "LbfgsbRestartEvent",
    "LbfgsbRestartReason",
    "NONFINITE_RESULT_STATUS",
    "OptimizerCallbackEvent",
    "OptimizerResult",
    "OptimizerResultFingerprint",
    "OptionsBase",
    "SCIPY_LBFGSB_UNRESOLVED_STALL_STATUS",
    "STATUS_CODES",
    "ScipyBFGSOptions",
    "ScipyBFGSCallbackEvent",
    "ScipyBounds",
    "ScipyLBFGSBOptions",
    "ScipyLBFGSBCallbackEvent",
    "ScipyLMOptions",
    "SimsoptAdamHostOptions",
    "SimsoptAdamHostCallbackEvent",
    "SimsoptAdamOptions",
    "SimsoptAdamCallbackEvent",
    "SimsoptBFGSOptions",
    "SimsoptBFGSCallbackEvent",
    "SimsoptLBFGSBOptions",
    "SimsoptLBFGSBCallbackEvent",
    "SimsoptLMQROptions",
    "SimsoptLMQRCallbackEvent",
    "SimsoptTraceLBFGSOptions",
    "SimsoptTraceLBFGSCallbackEvent",
    "fingerprint_optimizer_result",
]
