"""Regression panel against the colleague-supplied finite-I artifacts.

For each of the 4 current scans (01/02/10/20 kA), re-load the artifact at
HEAD, re-evaluate the math-layer invariants via the shared assertion
helpers in ``_helpers.py``, and assert ULP-tight equality against the
stored snapshot generated by ``_generate_colleague_snapshots.py``.

This panel is decoupled from the outer-loop (ALM / frontier / basin), from
the HW-spec audit, and from the colleague's optimizer trajectory. It
asserts only state-function reproducibility on the colleague's terminal
DOFs.

The assertion bodies live in ``_helpers.py`` so the end-to-end
negative-control tests (``test_negative_control.py``) can call the
*same* helpers with a monkey-patched math layer and verify the panel
actually catches injected drift.

See docs/regression_panel_colleague_artifacts_2026-05-11.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).parent))
import _helpers as H  # noqa: E402

from banana_opt.json_compat import load_boozer_finite_i  # noqa: E402


@pytest.fixture(params=H.ARTIFACT_KEYS, ids=lambda kA: f"{kA}kA")
def kA(request):
    artifact_path = H.ARTIFACTS[request.param]
    snap_path = H.SNAPSHOT_DIR / f"bsurf_opt_{request.param}kA.snapshot.json"
    if not artifact_path.exists():
        pytest.skip(f"colleague artifact not present at {artifact_path}")
    if not snap_path.exists():
        pytest.skip(
            f"snapshot not present at {snap_path}; "
            f"run python tests/regression/_generate_colleague_snapshots.py"
        )
    return request.param


@pytest.fixture
def loaded(kA):
    """Fresh load per test — avoids state leakage between mutating tests."""
    obj = load_boozer_finite_i(str(H.ARTIFACTS[kA]))
    obj.biotsavart.clear_cached_properties()
    return obj


@pytest.fixture
def snapshot(kA):
    with open(H.SNAPSHOT_DIR / f"bsurf_opt_{kA}kA.snapshot.json") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Metadata invariants (snapshot-direct; not via assertion helpers)
# ---------------------------------------------------------------------------


def test_I_matches_snapshot(loaded, snapshot):
    assert loaded.I == snapshot["I"]


def test_boozer_surface_class(loaded, snapshot):
    assert type(loaded).__name__ == snapshot["boozer_surface_class"]


# ---------------------------------------------------------------------------
# Math-layer invariants — each calls a shared helper from _helpers.py.
# The same helper is invoked by test_negative_control.py under a
# monkey-patched math source to verify the panel actually fails on drift.
# ---------------------------------------------------------------------------


def test_surface_geometry(loaded, snapshot):
    H.assert_surface_geometry_matches_snapshot(loaded, snapshot)


def test_volume(loaded, snapshot):
    H.assert_volume_matches_snapshot(loaded, snapshot)


def test_biot_savart_eval(loaded, snapshot):
    H.assert_biot_savart_eval_matches_snapshot(loaded, snapshot)


def test_coil0_geometry(loaded, snapshot):
    H.assert_coil0_geometry_matches_snapshot(loaded, snapshot)


def test_curve_curve_distance(loaded, snapshot):
    H.assert_curve_curve_distance_matches_snapshot(loaded, snapshot)


def test_boozer_kernel_path_b(loaded, snapshot):
    H.assert_boozer_kernel_path_b_matches_snapshot(loaded, snapshot)


# ---------------------------------------------------------------------------
# Reference-free physics / structural oracles — no snapshot needed.
# ---------------------------------------------------------------------------


def test_biot_savart_linearity_in_coil_currents(loaded):
    """Reference-free physics oracle. Asserts bit-equality."""
    surface = loaded.surface
    bs = loaded.biotsavart
    pts = H.eval_points(surface, seed=H.LINEARITY_PROBE_SEED, n=H.LINEARITY_PROBE_N)

    bs.clear_cached_properties()
    bs.set_points(pts)
    B0 = bs.B().copy()

    leaves, restore = H.scale_leaf_currents_in_memory(bs, 2.0)
    bs.clear_cached_properties()
    bs.set_points(pts)
    B1 = bs.B().copy()
    restore()

    np.testing.assert_array_equal(B1, 2.0 * B0)
    assert len(leaves) > 0


def test_biot_savart_cache_invalidation_under_no_op_mutation(loaded):
    """Probe `0bc13f225` invalidation lifecycle on the BiotSavart side."""
    surface = loaded.surface
    bs = loaded.biotsavart
    pts = H.eval_points(surface, seed=42, n=20)

    bs.clear_cached_properties()
    bs.set_points(pts)
    B0 = bs.B().copy()

    leaves = H.unique_leaf_currents(bs)
    leaf = leaves[0]
    was_fixed = leaf.dofs.all_fixed()
    saved_x = leaf.local_full_x.copy()

    leaf.unfix_all()
    leaf.x = leaf.x + 1.0
    bs.clear_cached_properties()
    bs.set_points(pts)
    _ = bs.B()

    leaf.unfix_all()
    leaf.x = saved_x.copy()
    if was_fixed:
        leaf.fix_all()
    bs.clear_cached_properties()
    bs.set_points(pts)
    B_restored = bs.B().copy()

    np.testing.assert_array_equal(B_restored, B0)
