"""Regression panel against the colleague-supplied finite-I artifacts.

For each of the 4 current scans (01/02/10/20 kA), re-load the artifact at
HEAD, re-evaluate the math-layer invariants, and assert ULP-tight equality
against the stored snapshot generated by
``_generate_colleague_snapshots.py``.

This panel is decoupled from the outer-loop (ALM / frontier / basin), from
the HW-spec audit, and from the colleague's optimizer trajectory. It asserts
only state-function reproducibility on the colleague's terminal DOFs.

See docs/regression_panel_colleague_artifacts_2026-05-11.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).parent))
import _helpers as H  # noqa: E402

import simsoptpp as sopp  # noqa: E402
from simsopt.geo.curveobjectives import CurveCurveDistance  # noqa: E402
from banana_opt.boozer_finite_current import (  # noqa: E402
    boozer_surface_residual_finite_I,
)
from banana_opt.json_compat import load_boozer_finite_i  # noqa: E402

_FIRST_N = 10


def _flat_prefix(arr):
    return np.ascontiguousarray(arr).reshape(-1)[:_FIRST_N]


@pytest.fixture(params=H.ARTIFACT_KEYS, ids=lambda kA: f"{kA}kA")
def kA(request):
    artifact_path = H.ARTIFACTS[request.param]
    snap_path = H.SNAPSHOT_DIR / f"bsurf_opt_{request.param}kA.snapshot.json"
    if not artifact_path.exists():
        pytest.skip(f"colleague artifact not present at {artifact_path}")
    if not snap_path.exists():
        pytest.skip(
            f"snapshot not present at {snap_path}; "
            f"run python tests/regression/_generate_colleague_snapshots.py"
        )
    return request.param


@pytest.fixture
def loaded(kA):
    """Fresh load per test — avoids state leakage between mutating tests."""
    obj = load_boozer_finite_i(str(H.ARTIFACTS[kA]))
    obj.biotsavart.clear_cached_properties()
    return obj


@pytest.fixture
def snapshot(kA):
    with open(H.SNAPSHOT_DIR / f"bsurf_opt_{kA}kA.snapshot.json") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Invariant assertions
# ---------------------------------------------------------------------------


def test_I_matches_snapshot(loaded, snapshot):
    assert loaded.I == snapshot["I"]


def test_boozer_surface_class(loaded, snapshot):
    assert type(loaded).__name__ == snapshot["boozer_surface_class"]


def test_surface_geometry(loaded, snapshot):
    gamma = loaded.surface.gamma()
    normal = loaded.surface.normal()
    expected = snapshot["surface_geometry"]

    assert list(gamma.shape) == expected["gamma_shape"]
    assert H.sha_full(gamma) == expected["gamma_sha256"], "gamma SHA mismatch"
    assert H.sha_full(normal) == expected["normal_sha256"], "normal SHA mismatch"

    # Diagnostic numeric comparison on the first 10 entries (rtol=1e-14)
    np.testing.assert_allclose(
        _flat_prefix(gamma),
        expected["gamma_sample_first10_flat"],
        rtol=1e-14, atol=0,
    )


def test_volume(loaded, snapshot):
    np.testing.assert_allclose(
        loaded.label.J(), snapshot["volume"], rtol=1e-14, atol=0
    )


def test_biot_savart_eval(loaded, snapshot):
    surface = loaded.surface
    bs = loaded.biotsavart
    bs.clear_cached_properties()
    pts = H.eval_points(surface, seed=H.EVAL_POINTS_SEED, n=H.EVAL_POINTS_N)
    bs.set_points(pts)
    B = bs.B().copy()
    dB = bs.dB_by_dX().copy()

    expected = snapshot["biot_savart_eval"]
    assert H.sha_full(pts) == expected["eval_points_sha256"], (
        "eval-points fixture diverged — regenerate snapshots"
    )
    assert H.sha_full(B) == expected["B_sha256"], "B SHA mismatch"
    assert H.sha_full(dB) == expected["dB_sha256"], "dB SHA mismatch"

    np.testing.assert_allclose(
        _flat_prefix(B), expected["B_sample_first10_flat"], rtol=1e-13, atol=0
    )
    np.testing.assert_allclose(
        _flat_prefix(dB), expected["dB_sample_first10_flat"], rtol=1e-12, atol=0
    )


def test_coil0_geometry(loaded, snapshot):
    curve = loaded.biotsavart.coils[0].curve
    cgamma = curve.gamma()
    cdg = curve.dgamma_by_dcoeff()
    expected = snapshot["coil0_geometry"]

    assert type(curve).__name__ == expected["type"]
    assert list(cgamma.shape) == expected["gamma_shape"]
    assert list(cdg.shape) == expected["dgamma_dcoeff_shape"]
    assert H.sha_full(cgamma) == expected["gamma_sha256"]
    assert H.sha_full(cdg) == expected["dgamma_dcoeff_sha256"]


def test_curve_curve_distance(loaded, snapshot):
    curves = [c.curve for c in loaded.biotsavart.coils]
    ccd = CurveCurveDistance(
        curves,
        minimum_distance=snapshot["curve_curve_distance"]["minimum_distance"],
        downsample=snapshot["curve_curve_distance"]["downsample"],
    )
    np.testing.assert_allclose(
        ccd.J(), snapshot["curve_curve_distance"]["value"], rtol=1e-12, atol=0
    )


def test_boozer_kernel_path_b(loaded, snapshot):
    surface = loaded.surface
    bs = loaded.biotsavart
    I = float(loaded.I)
    iota = snapshot["boozer_kernel_path_b"]["iota"]
    sum_abs_I = float(sum(abs(c.current.get_value()) for c in bs.coils))
    G0 = H.MU0 * sum_abs_I
    G_eff = G0 + iota * I

    # Re-derive G0 against snapshot to catch coil-current drift
    np.testing.assert_allclose(
        sum_abs_I, snapshot["boozer_kernel_path_b"]["sum_abs_I_coil"], rtol=1e-13
    )
    np.testing.assert_allclose(
        G_eff, snapshot["boozer_kernel_path_b"]["G_eff"], rtol=1e-13
    )

    # Wrapper path
    residual = boozer_surface_residual_finite_I(
        surface, iota, G0, bs, derivatives=0, weight_inv_modB=False, I=I
    )[0]
    wrapper_val = 0.5 * float(np.sum(residual ** 2))

    # Raw kernel path
    x = surface.gamma()
    bs.set_points(x.reshape(-1, 3).copy())
    B_at_surf = bs.B().reshape(x.shape)
    kernel_val = float(sopp.boozer_residual(
        G_eff, iota, surface.gammadash1(), surface.gammadash2(), B_at_surf, False
    ))
    kernel_at_G0 = float(sopp.boozer_residual(
        G0, iota, surface.gammadash1(), surface.gammadash2(), B_at_surf, False
    ))

    np.testing.assert_allclose(
        wrapper_val,
        snapshot["boozer_kernel_path_b"]["wrapper_residual_sqsum_half"],
        rtol=1e-12,
    )
    np.testing.assert_allclose(
        kernel_val,
        snapshot["boozer_kernel_path_b"]["raw_kernel_value"],
        rtol=1e-12,
    )

    # Wrapper ≈ raw kernel — finite-I round-trip equivalence
    np.testing.assert_allclose(wrapper_val, kernel_val, rtol=1e-12)

    # Finite-I non-trivial (witness that G_eff matters)
    assert not np.isclose(kernel_val, kernel_at_G0), (
        "kernel(G_eff) == kernel(G0): finite-I term is silently being ignored"
    )


def test_biot_savart_linearity_in_coil_currents(loaded):
    """Reference-free physics oracle. No snapshot. Asserts bit-equality."""
    surface = loaded.surface
    bs = loaded.biotsavart
    pts = H.eval_points(surface, seed=H.LINEARITY_PROBE_SEED, n=H.LINEARITY_PROBE_N)

    bs.clear_cached_properties()
    bs.set_points(pts)
    B0 = bs.B().copy()

    leaves, restore = H.scale_leaf_currents_in_memory(bs, 2.0)
    bs.clear_cached_properties()
    bs.set_points(pts)
    B1 = bs.B().copy()
    restore()

    np.testing.assert_array_equal(B1, 2.0 * B0)
    assert len(leaves) > 0


def test_biot_savart_cache_invalidation_under_no_op_mutation(loaded):
    """Probe `0bc13f225` invalidation lifecycle on the BiotSavart side.

    Eval B, mutate a leaf current, restore the leaf, re-eval B. Result must be
    bit-equal to the original. Catches stale-cache reads that survive a
    round-trip mutation.
    """
    surface = loaded.surface
    bs = loaded.biotsavart
    pts = H.eval_points(surface, seed=42, n=20)

    bs.clear_cached_properties()
    bs.set_points(pts)
    B0 = bs.B().copy()

    leaves = H.unique_leaf_currents(bs)
    leaf = leaves[0]
    was_fixed = leaf.dofs.all_fixed()
    saved_x = leaf.local_full_x.copy()

    leaf.unfix_all()
    leaf.x = leaf.x + 1.0  # touch the DOF
    bs.clear_cached_properties()
    bs.set_points(pts)
    _ = bs.B()  # forces recompute under perturbed state

    # restore
    leaf.unfix_all()
    leaf.x = saved_x.copy()
    if was_fixed:
        leaf.fix_all()
    bs.clear_cached_properties()
    bs.set_points(pts)
    B_restored = bs.B().copy()

    np.testing.assert_array_equal(B_restored, B0)
