"""Public backend runtime surface for the simsopt JAX lane."""

from .runtime import (
    VALID_BACKEND_MODES,
    BackendConfig,
    BackendPolicy,
    apply_jax_runtime_config,
    get_backend,
    get_backend_config,
    get_backend_mode,
    get_backend_policy,
    get_chunk_policy,
    get_compilation_cache_dir,
    get_compilation_cache_policy,
    get_debug_nans,
    get_jax_platform,
    get_provenance_label,
    get_tolerance_tier,
    get_transfer_guard,
    is_backend_strict,
    is_jax_backend,
    is_parity_mode,
    raise_if_strict_jax_fallback,
    requires_x64,
    set_backend,
    should_eagerly_configure_jax,
)

__all__ = [
    "VALID_BACKEND_MODES",
    "BackendConfig",
    "BackendPolicy",
    "apply_jax_runtime_config",
    "get_backend",
    "get_backend_config",
    "get_backend_mode",
    "get_backend_policy",
    "get_chunk_policy",
    "get_compilation_cache_dir",
    "get_compilation_cache_policy",
    "get_debug_nans",
    "get_jax_platform",
    "get_provenance_label",
    "get_tolerance_tier",
    "get_transfer_guard",
    "is_backend_strict",
    "is_jax_backend",
    "is_parity_mode",
    "raise_if_strict_jax_fallback",
    "requires_x64",
    "set_backend",
    "should_eagerly_configure_jax",
]
